woowacourse-teams/2022-dallog

- frontend/.prettierrc.json
- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/babel.config.js
- frontend/package.json
- frontend/src/@types/emotion.d.ts
- frontend/src/components/NavBar/NavBar.stories.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/index.html
- frontend/src/index.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/styles/theme.ts
- frontend/tsconfig.json
- frontend/webpack.config.js
- frontend/yarn.lock
> [feat] 내비게이션 바 레이아웃을 그린다.

- frontend/src/components/@common/Button.stories.tsx
- frontend/src/components/@common/Button.styles.ts
- frontend/src/components/@common/Button.tsx
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.stories.tsx
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.styles.ts
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.tsx
- frontend/src/index.html
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/styles/theme.ts
> [feat] 일정 추가 버튼 컴포넌트를 구현한다.

- .github/workflows/frontend-ci.yml
프론트엔드 Lint, Prettier, 빌드 체크를 위한 Github Actions 스크립트 추가
Closes #21
> [feat] 프론트엔드 CI Github Actions 스크립트를 추가한다.

- .github/workflows/backend-ci.yml
- .github/workflows/frontend-ci.yml
- frontend/package.json
백엔드 및 프론트 빌드 자동화 기능을 추가한다.
Closes #20
> [feat] 백엔드 및 프론트 빌드 자동화 기능을 추가한다.

- frontend/package.json
- frontend/public/mockServiceWorker.js
- frontend/src/components/@common/FieldSet/FieldSet.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/index.tsx
- frontend/src/mocks/browser.ts
- frontend/src/mocks/handlers.ts
- frontend/yarn.lock
> [feat] 일정 추가 기능을 구현한다.

- frontend/src/App.tsx
- frontend/src/components/@common/Button/Button.styles.ts
- frontend/src/components/@common/FieldSet/FieldSet.styles.ts
- frontend/src/components/@common/ModalPortal/ModalPortal.styles.ts
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/PageLayout/PageLayout.styles.ts
- frontend/src/components/PageLayout/PageLayout.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/styles/theme.ts
> [feat] 캘린더 페이지 레이아웃을 그린다.

- frontend/.eslintrc.json
- frontend/.storybook/preview-body.html
- frontend/package.json
- frontend/src/@types/index.ts
- frontend/src/App.tsx
- frontend/src/api/schedule.ts
- frontend/src/components/@common/FieldSet/FieldSet.styles.ts
- frontend/src/components/Calendar/Calendar.styles.ts
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/PageLayout/PageLayout.styles.ts
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/constants/index.ts
- frontend/src/index.html
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/utils/index.ts
- frontend/yarn.lock
> [refactor] 1차 스프린트 리팩토링을 진행한다.

- backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
- backend/src/main/java/com/allog/dallog/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/category/dto/request/CategoryCreateRequest.java
- backend/src/main/java/com/allog/dallog/category/exception/InvalidCategoryException.java
- backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
- backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryTest.java
- backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
> [feat] 카테고리 생성 기능을 구현한다.

- backend/src/main/java/com/allog/dallog/DallogApplication.java
- backend/src/main/java/com/allog/dallog/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/global/config/JpaConfig.java
- backend/src/main/java/com/allog/dallog/global/domain/BaseEntity.java
- backend/src/main/java/com/allog/dallog/schedule/domain/Schedule.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
JPA Auditing 적용. 생성일시와 수정일시를 BaseEntity에 추가하여 모든 Entity가 상속받도록 함.
이전 PR이 머지가 안 되어서 커밋 기록이 섞여있음.
Closes #45
> [feat] JPA Auditing을 적용한다. 

- frontend/.prettierrc.json
- frontend/.storybook/preview.js
- frontend/package.json
- frontend/src/components/@common/Button/Button.stories.tsx
- frontend/src/components/@common/FieldSet/FieldSet.stories.tsx
- frontend/src/components/@common/FieldSet/FieldSet.tsx
- frontend/src/components/@common/ModalPortal/ModalPortal.tsx
- frontend/src/components/NavBar/NavBar.stories.tsx
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.stories.tsx
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/index.tsx
- frontend/src/mocks/browser.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/yarn.lock
> [feat] import 순서 규칙을 추가한다.

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/constants/index.ts
- frontend/src/index.tsx
- frontend/yarn.lock
라우팅에 사용되는 path는 `constants/index.ts`의 `PATH`에 `{페이지_컴포넌트}: '{경로}'` 형식으로 관리됩니다.
Closes #59
> [feat] 리액트 라우터를 도입한다.

- frontend/.storybook/main.js
- frontend/src/@types/category.ts
- frontend/src/@types/index.ts
- frontend/src/api/categories.ts
- frontend/src/components/CategoryItem/CategoryItem.stories.tsx
- frontend/src/components/CategoryItem/CategoryItem.styles.ts
- frontend/src/components/CategoryItem/CategoryItem.tsx
- frontend/src/components/CategoryList/CategoryList.stories.tsx
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/useIntersect.ts
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
> [feat] 카테고리 조회 컴포넌트를 구현한다. 

- frontend/src/components/@common/FieldSet/FieldSet.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/utils/index.ts
- frontend/yarn.lock
- 스토리북 절대경로 에러는 이전 PR이 merge되면 해결될 예정입니다.
Closes #47
> [feat] 일정 추가 모달에서 종일 기능을 구현한다.

- frontend/src/components/@common/FieldSet/FieldSet.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.stories.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.styles.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- 카테고리 추가를 어떤 페이지에서 어떻게 하는 게 좋을지가 확정되지 않아 우선적으로 모달 컴포넌트만 구현하였습니다.
- 일정 생성과 동일하게 컴포넌트 구현 PR과 기능 구현 PR을 나누려고 합니다.
Closes #41
> [feat] 카테고리 생성 모달 컴포넌트를 구현한다.

- frontend/.storybook/preview.js
- frontend/src/App.tsx
- frontend/src/api/login.ts
- frontend/src/components/@common/Button/Button.tsx
- frontend/src/components/LoginModal/LoginModal.styles.ts
- frontend/src/components/LoginModal/LoginModal.tsx
- frontend/src/components/NavBar/NavBar.stories.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/PageLayout/PageLayout.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/StartPage/StartPage.tsx
- 시작 페이지 임시 경로: `/start`
- 달력 페이지 임시 경로: `/auth`
svg와 관련된 에러를 아직 해결하지 못해서 이미지는 삽입하지 않았습니다
참고 부탁드립니다 얼른 해결하겠습니다!
react-query를 활용하지 않고도 간단하게 해결할 수 있을 때에도 전자가 나을까요~? 🤔
Closes #38
> [feat] 소셜 로그인 모달 컴포넌트를 구현한다.

- backend/src/test/java/com/allog/dallog/auth/service/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/auth/support/JwtTokenProviderTest.java
- backend/src/test/java/com/allog/dallog/member/domain/MemberRepositoryTest.java
- backend/src/test/java/com/allog/dallog/member/service/MemberServiceTest.java
- `JwtTokenProvider` 테스트 코드 추가
- `MemberRepository` 의 `findByEmail` 테스트 코드 추가
- `MemberService` 의 테스트 코드 추가
> 참고 : `infrastructure` 패키지의 구현체는 외부 API (구글 등)에 의존하므로 테스트코드 작성이 불가능합니다.
본 브랜치는 PR #53 의 브랜치에서 생성되었습니다. #53  이 Merge 되면, 본 브랜치를 Rebase 한 후 force push 할 예정입니다. 리뷰는 1eee7f7e6be379dbb22a07d4c755c04adb4f3796 커밋부터 해주시면 됩니다 😊
Closes #54
> [feat] 회원 및 소셜 로그인 관련 코드에 대한 테스트 코드를 추가한다.

- frontend/src/@types/profile.ts
- frontend/src/App.tsx
- frontend/src/api/profile.ts
- frontend/src/components/@common/Button/Button.tsx
- frontend/src/constants/index.ts
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/MyPage/MyPage.styles.ts
- frontend/src/pages/MyPage/MyPage.tsx
- accesstoken은 임의로 지정했습니다. (localStorage 로직 없음)
Closes #39
> [feat] 마이 페이지 컴포넌트를 구현한다.

- frontend/package.json
- frontend/src/@types/custom.d.ts
- frontend/webpack.config.js
- frontend/yarn.lock
> [feat] file loader 및 react-icons를 설치한다.

- backend/src/main/java/com/allog/dallog/member/exception/InvalidMemberException.java
- backend/src/main/java/com/allog/dallog/subscription/domain/Subscription.java
- backend/src/main/java/com/allog/dallog/subscription/exception/InvalidSubscriptionException.java
- backend/src/test/java/com/allog/dallog/fixture/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/fixture/MemberFixtures.java
- backend/src/test/java/com/allog/dallog/subscription/domain/SubscriptionTest.java
> [feat] 구독 관련 엔티티를 설계한다. 

- backend/src/main/java/com/allog/dallog/auth/controller/AuthController.java
- backend/src/main/java/com/allog/dallog/auth/dto/OAuthUriResponse.java
- backend/src/main/java/com/allog/dallog/auth/service/AuthService.java
- backend/src/main/java/com/allog/dallog/auth/support/OAuthUri.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/GoogleOAuthUri.java
- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- OAuthUriResponse 생성
- Endpoint로 네이밍된 클래스 이름 변경
관련 API(auth) 명세가 변경되었습니다. 노션 API 설계문서를 확인해주세요!
Closes #92
> [feat] OAuth 인증 URI에 대한 DTO를 추가한다. 

- frontend/.prettierrc.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/api/login.ts
- frontend/src/atoms/index.ts
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/components/LoginModal/LoginModal.styles.ts
- frontend/src/components/LoginModal/LoginModal.tsx
- frontend/src/components/ProtectRoute/index.tsx
- frontend/src/constants/index.ts
- frontend/src/index.tsx
- frontend/src/pages/AuthPage/AuthPage.tsx
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/styles/theme.ts
- frontend/src/utils/index.ts
- frontend/yarn.lock
> [feat] 컴포넌트의 인가를 처리한다.

- backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
카테고리의 테스트 픽스처 생성 및 적용
Closes #99
> [feat] 카테고리의 테스트 픽스처를 만든다.

- backend/src/main/java/com/allog/dallog/subscription/controller/SubscriptionController.java
- backend/src/main/java/com/allog/dallog/subscription/dto/response/SubscriptionsResponse.java
- backend/src/main/java/com/allog/dallog/subscription/repository/SubscriptionRepository.java
- backend/src/main/java/com/allog/dallog/subscription/service/SubscriptionService.java
- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/auth/service/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/MemberFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/SubscriptionFixtures.java
- backend/src/test/java/com/allog/dallog/subscription/domain/SubscriptionTest.java
- backend/src/test/java/com/allog/dallog/subscription/repository/SubscriptionRepositoryTest.java
- backend/src/test/java/com/allog/dallog/subscription/service/SubscriptionServiceTest.java
구독 중인 카테고리 조회 기능을 구현한다.
Closes #80
> [feat] 구독 중인 카테고리 조회 기능을 구현한다.

- frontend/.storybook/preview.js
- frontend/src/@types/subscription.ts
- frontend/src/api/subscription.ts
- frontend/src/components/CategoryItem/CategoryItem.styles.ts
- frontend/src/components/CategoryItem/CategoryItem.tsx
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/SubscribeButton/SubscribeButton.stories.tsx
- frontend/src/components/SubscribeButton/SubscribeButton.styles.ts
- frontend/src/components/SubscribeButton/SubscribeButton.tsx
- frontend/src/constants/index.ts
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
- 구독목록을 전역에서 관리하지 않았습니다.
Closes #70
> [feat] 유저별 카테고리 구독하기 기능을 구현한다.

- backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
- backend/src/main/java/com/allog/dallog/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
- API 설계
- 자신이 생성한 카테고리 목록을 조회 인수테스트 작성
- 기능 구현
Closes #96
> [feat] 자신이 생성한 카테고리 목록을 조회하는 기능을 구현한다.

- frontend/.storybook/preview.js
- frontend/src/api/subscription.ts
- frontend/src/components/CategoryItem/CategoryItem.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/constants/index.ts
- frontend/src/mocks/handlers.ts
> [feat] 유저별 카테고리 구독 해제 기능을 구현한다.

- backend/src/main/java/com/allog/dallog/auth/exception/NoPermissionException.java
- backend/src/main/java/com/allog/dallog/subscription/controller/SubscriptionController.java
- backend/src/main/java/com/allog/dallog/subscription/repository/SubscriptionRepository.java
- backend/src/main/java/com/allog/dallog/subscription/service/SubscriptionService.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/subscription/repository/SubscriptionRepositoryTest.java
- backend/src/test/java/com/allog/dallog/subscription/service/SubscriptionServiceTest.java
구독 중인 카테고리 구독 취소 기능을 구현한다.
Closes #79
> [feat] 구독 중인 카테고리 구독 취소 기능을 구현한다.

- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/MemberAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/auth/service/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/member/domain/MemberRepositoryTest.java
- backend/src/test/java/com/allog/dallog/member/service/MemberServiceTest.java
유저와 인증의 테스트 픽스처를 만든다.
Closes #104
> [test] 유저와 인증의 테스트 픽스처를 만든다. 

- backend/src/main/resources/application.properties
- backend/src/main/resources/data.sql
- backend/src/test/resources/application.properties
원할한 데이터 연동을 위해 초기 데이터를 세팅한다.
Closes #119
> [feat] 초기 데이터를 세팅한다.

- backend/src/main/java/com/allog/dallog/auth/service/AuthService.java
- backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
- backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
- backend/src/main/java/com/allog/dallog/member/service/MemberService.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/auth/service/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/MemberFixtures.java
- backend/src/test/java/com/allog/dallog/member/service/MemberServiceTest.java
카테고리를 단건 조회하는 기능을 구현한다.
Closes #109
> [feat] 카테고리를 단건 조회하는 기능을 구현한다.

- README.md
README에 Contributors를 추가합니다.
Closes #130
> [docs] README에 Contributors를 추가한다.

- backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
- backend/src/main/java/com/allog/dallog/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/category/dto/request/CategoryUpdateRequest.java
- backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CommonAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/member/domain/MemberRepositoryTest.java
- backend/src/test/java/com/allog/dallog/schedule/domain/ScheduleRepositoryTest.java
- backend/src/test/resources/application.properties
- frontend/src/components/@common/Button/Button.tsx
자신이 생성한 카테고리를 수정 및 삭제하는 기능을 구현한다.
Closes #97
> [feat] 자신이 생성한 카테고리를 수정 및 삭제하는 기능을 구현한다.

- frontend/.prettierrc.json
- frontend/src/App.tsx
- frontend/src/components/@common/PageLayout/PageLayout.styles.ts
- frontend/src/components/@common/PageLayout/PageLayout.tsx
- frontend/src/components/Calendar/Calendar.styles.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryItem/CategoryItem.tsx
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/ProtectRoute/index.tsx
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/MyPage/MyPage.styles.ts
- frontend/src/pages/MyPage/MyPage.tsx
- frontend/src/recoil/atoms/index.ts
- frontend/src/recoil/selectors/index.ts
> [refactor] 내비게이션 바 및 사이드 바 관련 컴포넌트를 리팩토링한다.

- backend/src/main/java/com/allog/dallog/global/config/PropertiesConfig.java
- backend/src/main/java/com/allog/dallog/global/config/properties/GoogleProperties.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/GoogleOAuthUri.java
- backend/src/main/resources/application.yml
- backend/src/test/resources/application.yml
프로젝트 설정을 위한 application.yml의 특정 값을 객체로 매핑한다.
Closes #141
> [feat] 프로젝트 설정파일을 객체로 매핑한다.

- backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
- backend/src/test/resources/truncate.sql
테스트 격리 방식을 변경한다.
[테스트 시간 비교](https://github.com/woowacourse-teams/2022-dallog/issues/162#issuecomment-1196259582)
Closes #162
> [feat] 테스트 격리 방식을 변경한다. 

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/presentation/CategoryController.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/resources/application.yml
- 카테고리 삭제 및 수정 할 때 대상 카테고리가 존재하지 않으면 예외가 정상적으로 발생하는지 확인하는 테스트 코드 추가
- 존재하지 않는 ID로 카테고리를 단건 조회할 때 정상적으로 예외가 발생하는지에 대한 테스트 코드 추가
- Pageable의 최대 페이지 사이즈를 100으로 제한
- 누락된 final 키워드 추가
Closes #144
> [feat] Category의 예외 케이스 핸들링 로직을 추가한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/exception/OAuthException.java
- backend/src/test/java/com/allog/dallog/common/fixtures/MemberFixtures.java
- backend/src/test/java/com/allog/dallog/domain/member/domain/MemberTest.java
- GoogleOAuthClient 예외 처리 및 함수 로직 변경
- Member의 생성자 파라미터 순서 변경
Closes #150
> [refactor] Auth와 Member의 예외 케이스 핸들링 로직을 추가한다.

- backend/src/main/java/com/allog/dallog/global/dto/ErrorResponse.java
- backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java
글로벌 Exception Handler를 구현한다. 
Closes #146
> [feat] 글로벌 Exception Handler를 구현한다.

- frontend/src/App.tsx
- frontend/src/components/SnackBar/SnackBar.styles.ts
- frontend/src/components/SnackBar/SnackBar.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/useSnackBar.ts
- frontend/src/recoil/atoms/index.ts
- 스토리북은 추후에 수정할 예정입니다.
Closes #164
> [feat] 스낵바를 구현한다.

- frontend/src/api/category.ts
- frontend/src/components/Calendar/Calendar.styles.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.styles.ts
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/constants/index.ts
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- overflow 속성은 사이드 바 컴포넌트에 존재
- 목록별 스크롤이나 무한 스크롤 기능은 논의 후 개발 예정
Closes #83
> [feat] 유저별 생성 카테고리 조회 기능을 구현한다.

- backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/DatabaseCleaner.java
- backend/src/test/java/com/allog/dallog/common/DatabaseCleanup.java
- backend/src/test/resources/truncate.sql
> [test] 테스트 격리 방식을 개선한다.

- backend/src/docs/asciidoc/auth.adoc
- backend/src/docs/asciidoc/index.adoc
- backend/src/test/java/com/allog/dallog/common/fixtures/AuthFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/presentation/AuthControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/member/presentation/MemberControllerTest.java
Auth API 문서 작성을 위한 컨트롤러 테스트 작성
Closes #168
> [test] Auth에 대한 컨트롤러 테스트를 추가한다.

- backend/src/docs/asciidoc/index.adoc
- backend/src/docs/asciidoc/subscription.adoc
- backend/src/main/java/com/allog/dallog/domain/subscription/presentation/SubscriptionController.java
- backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/MemberFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/SubscriptionFixtures.java
- backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
Subscription에 대한 컨트롤러 테스트를 추가하여 API 문서를 생성한다.
Closes #148
> [test] Subscription에 대한 컨트롤러 테스트를 추가한다. 

- backend/src/docs/asciidoc/category.adoc
- backend/src/docs/asciidoc/subscription.adoc
- backend/src/test/java/com/allog/dallog/domain/category/presentation/CategoryControllerTest.java
원활한 작업을 위해 아직 머지가 되지 않은 `hyeonic:feature/148-subscription-rest-docs` 브랜치로 리베이스 후 작업하였습니다. #173 PR이 머지되면, 이 PR을 머지하도록 하겠습니다.
Closes #147
> [test] Category에 대한 컨트롤러 테스트를 추가한다.

- frontend/src/constants/index.ts
- frontend/src/pages/MyPage/MyPage.styles.ts
- frontend/src/pages/MyPage/MyPage.tsx
- frontend/src/styles/theme.ts
- frontend/src/utils/index.ts
> [feat] 로그아웃 기능을 구현한다.

- backend/.gitignore
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/global/error/Reporter.java
- backend/src/main/java/com/allog/dallog/global/error/dto/ErrorReportRequest.java
- backend/src/main/java/com/allog/dallog/global/error/dto/ErrorResponse.java
- backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/infrastructure/report/DiscordReporter.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/allog/dallog/common/config/TestConfig.java
- backend/src/test/java/com/allog/dallog/domain/auth/presentation/AuthControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/category/presentation/CategoryControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/member/presentation/MemberControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/presentation/ScheduleControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
- backend/src/test/java/com/allog/dallog/infrastructure/oauth/report/DummyReporter.java
- backend/src/test/resources/application.yml
- `application.yml` 에 logback 관련 설정 추가 
- `ControllerAdvice` 에서 예상하지 못한 예외 발생 시 `ERROR` 레벨로 로깅
Closes #182
> [feat] 백엔드 서버 로깅 기능을 구현하고, 로그를 파일로 저장한다. 

- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/mocks/data.ts
- frontend/src/utils/index.ts
> [feat] 구독 시 색상 랜덤 지정을 구현한다.

- backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
- backend/src/main/java/com/allog/dallog/domain/subscription/dto/response/SubscriptionResponse.java
- backend/src/main/resources/data.sql
- backend/src/test/java/com/allog/dallog/common/fixtures/SubscriptionFixtures.java
- backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionTest.java
구독 생성 시 일정 조회 필터링을 위한 체크 필드를 추가한다.
Closes #201
> [feat] 구독 생성 시 필터링을 위한 체크 필드를 추가한다.

- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/common/BaseEntity.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
도메인 내부에 `global` 패키지 의존성을 줄이기 위해 `BaseEntity`의 위치를 변경한다.
Closes #198
> [feat] BaseEntity의 패키지 위치를 변경한다.

- frontend/src/@types/index.ts
- frontend/src/@types/schedule.ts
- frontend/src/api/schedule.ts
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/hooks/useCalendar.ts
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- frontend/src/utils/index.ts
- getScheduleDB는 임시 mockData입니다.
- mocking을 위해 scheduleDB를 필터링하는 과정이 오버엔지니어링이라는 생각이 들었습니다.
Closes #188
> [feat] 일정 조회 기능을 수정한다.

- frontend/src/@types/index.ts
- frontend/src/api/category.ts
- frontend/src/components/@common/Fieldset/Fieldset.stories.tsx
- frontend/src/components/@common/Fieldset/Fieldset.styles.ts
- frontend/src/components/@common/Fieldset/Fieldset.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryList/CategoryList.stories.tsx
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
> [feat] 카테고리 이름 검색 기능을 구현한다.

- backend/src/docs/asciidoc/category.adoc
- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/category/presentation/CategoryController.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/category/presentation/CategoryControllerTest.java
카테고리 제목 검색 기능을 추가한다.
Closes #200
> [feat] 카테고리 제목 검색 기능을 추가한다.

- .github/workflows/backend-ci.yml
backend ci를 위한 jdk를 변경한다.
Closes #212
> [feat] github actions의 jdk를 변경한다.

- backend/src/docs/asciidoc/member.adoc
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/domain/member/dto/MemberUpdateRequest.java
- backend/src/main/java/com/allog/dallog/domain/member/presentation/MemberController.java
- backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/presentation/CategoryControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/member/domain/MemberTest.java
- backend/src/test/java/com/allog/dallog/domain/member/presentation/MemberControllerTest.java
회원의 닉네임을 수정하는 기능을 구현한다.
Closes #223
> [feat] 회원의 닉네임을 수정하는 기능을 추가한다.

- frontend/src/components/NavBar/NavBar.tsx
> 비로그인 시 사이드바를 숨긴다.

- frontend/src/api/profile.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/MyPage/MyPage.styles.ts
- frontend/src/pages/MyPage/MyPage.tsx
> [feat] 회원 닉네임을 수정한다.

- frontend/package.json
- frontend/src/@types/subscription.ts
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.styles.ts
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
> [feat] 구독 카테고리 목록의 체크 박스 필터링 기능을 구현한다.

- frontend/package.json
- frontend/src/components/@common/Spinner/Spinner.stories.tsx
- frontend/src/components/@common/Spinner/Spinner.styles.ts
- frontend/src/components/@common/Spinner/Spinner.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.styles.ts
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.styles.ts
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/MyPage/MyPage.styles.ts
- frontend/src/pages/MyPage/MyPage.tsx
스켈레톤이 더 유익한 경험이 있을 수 있는 부분은 나중에 스켈레톤으로 변경하면 좋을 것 같아요.
Closes #235
> [feat] 로딩 스피너 컴포넌트를 구현한다.

- backend/src/docs/asciidoc/schedule.adoc
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleCreateRequest.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/ScheduleResponse.java
- backend/src/main/java/com/allog/dallog/domain/schedule/exception/NoSuchScheduleException.java
- backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/ScheduleAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/presentation/ScheduleControllerTest.java
- 일정 단건 조회 기능 생성
- 일정 단건 조회 문서 테스트 생성
- 일정 단건 조회 서비스, 인수테스트 생성
Closes #207
> [feat] 일정 단건 조회 기능을 구현한다.

- backend/src/docs/asciidoc/schedule.adoc
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleUpdateRequest.java
- backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/ScheduleAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/presentation/ScheduleControllerTest.java
일정 삭제 기능을 구현하였습니다.
Closes #209
> [feat] 일정 삭제 기능을 구현한다.

- backend/src/docs/asciidoc/subscription.adoc
- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
- backend/src/main/java/com/allog/dallog/domain/subscription/dto/SubscriptionUpdateRequest.java
- backend/src/main/java/com/allog/dallog/domain/subscription/presentation/SubscriptionController.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/SubscriptionAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
> [feat] 구독 수정 기능을 구현한다.

- backend/build.gradle
MySQL 연동을 위한 라이브러리를 추가한다.
Closes #240
> [feat] MySQL 연동을 위한 라이브러리를 추가한다. 

- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
isLoading관련 코드가 깔끔하지 않습니다. 리팩토링이 필요하나 시간 상 PR 올리겠습니다!
Closes #245
> [feat] 달력 뷰 렌더링과 일정 조회 기능을 분리한다.

- frontend/src/api/schedule.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/utils/date.ts
추후 리팩토링으로 코드 가독성을 높이겠습니다 😇🔫
종일 일정에 대한 날짜 및 시간 input value에 대한 논의가 필요합니다!
Closes #244
> [fix] 일정 추가 요청을 수정한다.

- frontend/src/@types/subscription.ts
- frontend/src/api/subscription.ts
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
> [feat] 구독 카테고리 목록 수정 기능을 구현한다.

- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> [fix] 종일 일정 추가 시 하루의 일정만 추가되는 에러를 수정한다.

- .github/workflows/frontend-ci.yml
- frontend/.storybook/preview.js
- frontend/jest.config.js
- frontend/package.json
- frontend/setupFile.js
- frontend/src/components/@common/Button/Button.stories.tsx
- frontend/src/components/@common/Button/Button.test.tsx
- frontend/src/components/@common/Fieldset/Fieldset.test.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
- frontend/yarn.lock
> [test] 버튼과 입력 필드 컴포넌트 테스트를 추가한다. 

- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
> [feat] 일정 수정 기능을 구현한다.

- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/mocks/handlers.ts
> [fix] '나의 카테고리' 컴포넌트의 변경 사항을 '구독 카테고리' 컴포넌트에 실시간으로 반영한다.

- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleCreateRequest.java
일정 메모의 공백 입력을 허용한다.
Closes #261
> [fix] 일정 메모의 공백 입력을 허용한다.

- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/global/error/dto/ErrorReportRequest.java
로거가 StackTrace도 함께 로깅하여 `.log` 파일로 에러 추적을 더 쉽게 할 수 있도록 개선하였습니다.
Closes #265
> [feat] 로거가 StackTrace도 함께 로깅하도록 개선한다. 

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
- jenkins/frontend-prod.jenkinsfile
젠킨스의 빌드가 성공 혹은 실패 했을 때 해당 사항을 디스코드에 알리는 스크립트를 추가한다.
Closes #272
> [ci] 젠킨스의 빌드가 성공 혹은 실패 했을 때 해당 사항을 디스코드에 알리는 스크립트를 추가한다.

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
#273 PR 버전에서 파이프라인 문법 오류가 존재함을 확인했습니다. 이를 해결하기 위해 #272 이슈를 다시 열고 PR 올립니다!
Closes #272
> [ci] 젠킨스 파이프라인 문법 오류 수정

- backend/src/main/java/com/allog/dallog/global/config/WebConfig.java
- backend/src/test/resources/application.yml
특정 URI의 요청만 cors 처리할 수 있도록 수정한다.
서브 모듈을 수정하였습니다. 관련 PR이 merge되면 서브 모듈을 최신화 시켜주세요!
Closes #258
> [feat] 특정 url의 요청만 cors 처리할 수 있도록 수정한다.

- backend/src/docs/asciidoc/schedule.adoc
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponse.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
- backend/src/test/java/com/allog/dallog/domain/schedule/presentation/ScheduleControllerTest.java
일정 전체 조회 관련 기능 API 문서를 작성했습니다.
Closes #275
> [docs] 일정 전체 조회 관련 기능 API 문서를 작성한다. 

- frontend/src/styles/GlobalStyle.tsx
- frontend/src/styles/theme.ts
스크롤 바 색상이 변경되었는데 한 번 확인 부탁드려요!
노랑 주황 파랑의 기본 색상은 _500 번대로 지정했습니다!
Closes #291
> [style] 메인 색상을 변경한다. 

- frontend/src/recoil/atoms/index.ts
> 사이드 바의 default 상태를 변경한다.

- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/utils/date.ts
> [feat] 달력에 오늘 날짜를 표시한다.

- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
스타일에 대한 피드백 주시면 감사하겠습니다. (eg: 바가 얇다, 두껍다, 글씨가 잘 안보인다 등..)
Closes #294
> [style] 단일 일정의 렌더링 방식을 변경한다.

- backend/src/docs/asciidoc/subscription.adoc
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryCreateRequest.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/presentation/CategoryControllerTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
개인 카테고리 기능을 구현했습니다.
Closes #277
> [feat] 유저 개인 카테고리 기능을 구현한다.

- frontend/src/components/@common/Fieldset/Fieldset.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/MyCategoryItem/MyCategoryItem.style.ts
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.styles.ts
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
UI 변경점에 대해서 말씀해주셔도 너무 좋을 것 같아요! 제 뇌피셜로 만들어진 UI라... 괜찮을지 모르겠네요~!
Closes #296
> [feat] 나의 카테고리 목록을 카테고리 페이지로 이동한다.

- frontend/src/components/SideBar/SideBar.tsx
> [fix] 비로그인 상태에 사이드 바가 보이는 에러를 수정한다.

- backend/src/main/resources/data.sql
data.sql 의 `categories` 테이블에 `personal` 필드를 추가하였습니다.
Closes #322
> [fix] Category 스키마 변경으로 인해 data.sql를 수정한다.

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
develop에 적용된 submodule을 활용하도록 젠킨스 스크립트 파일을 수정한다.
Closes #326
> [fix] develop에 적용된 submodule을 활용하도록 젠킨스 스크립트 파일을 수정한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/global/config/WebConfig.java
- backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
- backend/src/main/java/com/allog/dallog/presentation/MemberController.java
- backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
- backend/src/main/java/com/allog/dallog/presentation/SubscriptionController.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthenticationPrincipal.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthenticationPrincipalArgumentResolver.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthorizationExtractor.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/SubscriptionControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/auth/AuthControllerTest.java
컨트롤러를 도메인 밖으로 옮겨 presentation으로 묶는다.
Closes #328
> [feat] 디렉토리 구조를 변경한다.

- jenkins/frontend-prod.jenkinsfile
프론트엔드 배포 파이프라인 스크립트를 수정한다. 
Closes #330
> [ci] 프론트엔드 배포 파이프라인 스크립트를 수정한다. 

- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/schedules/ScheduleType.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> [refactor] Schedule.getSubscriptionColor() 예외가 발생하면 커스텀 예외를 던지도록 변경한다.

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/DateRangeRequest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleRepositoryTest.java
- backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java
> [refactor] scheduleService.getSchedulesFrom()의 성능을 개선한다. 

- frontend/src/components/@common/Skeleton/Skeleton.stories.tsx
- frontend/src/components/@common/Skeleton/Skeleton.styles.ts
- frontend/src/components/@common/Skeleton/Skeleton.tsx
- frontend/src/components/CategoryList/CategoryList.fallback.stories.tsx
- frontend/src/components/CategoryList/CategoryList.fallback.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.fallback.stories.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.fallback.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.styles.ts
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.fallback.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.styles.ts
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/Profile/Profile.fallback.stories.tsx
- frontend/src/components/Profile/Profile.fallback.tsx
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/pages/CategoryPage/CategoryPage.tsx
> [feat]  나의 구독 목록 스켈레톤 UI 작성  카테고리 목록 스켈레톤 UI 작성

- frontend/src/api/schedule.ts
일정 조회 API 변경에 대응한다.
```
?startDateTime=2022-06-27T00:00&endDateTime=2022-08-05T11:59 HTTP/1.1
```
이런식으로 시작과 끝에 시간을 붙여주는것으로 변경되었습니다😁
Closes #347
> [refactor] 일정 조회 API 변경에 대응한다.

- backend/src/docs/asciidoc/member.adoc
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/presentation/MemberController.java
- backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/MemberAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java
회원 탈퇴 기능을 구현하였습니다.
Closes #334
> [feat] 회원 탈퇴 API를 구현한다. 

- backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/CategorySubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/RegisterServiceTest.java
`ServiceTest`의 트랜잭션 애노테이션을 제거하고 DB `Truncate` 를 적용
Closes #349
> [test] 테스트 코드의 불필요한 트랜잭션을 제거한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthToken.java
- backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepository.java
- backend/src/main/java/com/allog/dallog/domain/auth/dto/OAuthMember.java
- backend/src/main/java/com/allog/dallog/domain/auth/exception/NoSuchOAuthTokenException.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/global/config/properties/GoogleProperties.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/dto/UserInfo.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/GoogleOAuthUri.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/common/fixtures/AuthFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/OAuthFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/domain/OAuthTokenTest.java
- backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java
구글의 토큰 정보를 저장한다.
서브모듈이 변경 되었습니다!  merge가 되면 `git submodule update --init`을 통해 해당 커밋에 맞는 설정 파일을 적용해주세요!
Closes #333
> [feat] 구글의 토큰 정보를 저장한다.

- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
일정을 hover 할 때에는 날짜 hover 스타일이 적용되지 않도록 처리하려고 했는데 생각보다 오래 걸리더라고요 🥲
나중의 태스크로 미뤄 처리하도록 하겠습니다~!
Closes #359
> [style] 날짜 hover 스타일을 변경한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/auth/application/TokenProvider.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CommonAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
- backend/src/test/java/com/allog/dallog/common/config/OAuthConfig.java
- backend/src/test/java/com/allog/dallog/common/config/TokenConfig.java
- backend/src/test/java/com/allog/dallog/common/fixtures/AuthFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/JwtTokenProviderTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/StubTokenProvider.java
- backend/src/test/java/com/allog/dallog/infrastructure/oauth/client/StubTokenProvider.java
- backend/src/test/java/com/allog/dallog/presentation/ControllerTest.java
웹페이지 로딩을 할 때, 토큰의 만료시간이 지나면 예외발생
웹페이지 로딩을 할 때, 토큰이 올바르지 않으면 예외발생
Closes #356
> [feat] 웹페이지 로딩 시, 토큰이 유효한지 검증한다. 

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/RegisterService.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
- backend/src/main/java/com/allog/dallog/presentation/MemberController.java
- backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
- backend/src/main/java/com/allog/dallog/presentation/SubscriptionController.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/CalendarServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/CategorySubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/RegisterServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepositoryTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java
- backend/src/test/java/com/allog/dallog/presentation/SubscriptionControllerTest.java
- service 구조 변경
- 양방향 mapping 제거
변경 사항이 많아 꼼꼼히 봐주시길 부탁드립니다.
리팩토링 하면서 생긴 의문이나 고민되는 부분은 이슈에 기록해두었습니다. 이슈 #341 꼭 확인부탁드립니다!
Closes #341
> [refactor] Service 구조를 변경한다.

- .github/workflows/backend-analysis.yml
- .github/workflows/backend-ci.yml
- .github/workflows/frontend-ci.yml
- backend/build.gradle
소나큐브 관련 워크플로우의 오류를 수정합니다.
Closes #276
> [ci] 소나큐브 관련 워크플로우의 오류를 수정한다.

- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/exception/OAuthException.java
제어할 수 없는 외부 영역에서 던지는 예외 상황을 로깅한다. 외부 서버에서 던지는 예외 상황을 빠르게 확인하기 위한 로깅을 진행한다.
Closes #352
> [feat] 제어할 수 없는 외부 영역에서 던지는 예외 상황을 로깅한다.

- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/pages/StartPage/StartPage.styles.ts
> [style] 시작 페이지와 카테고리 페이지의 스타일을 수정한다.

- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
자신이 생성한 카테고리는 구독 취소할 수 없게 하는 기능을 구현한다.
Closes #285
> [feat] 자신이 생성한 카테고리는 구독 취소할 수 없게 하는 기능을 구현한다.

- jenkins/backend-dev.jenkinsfile
젠킨스를 통해 CD 시점에 소나큐브로 정적 분석을 실행하도록 변경
Closes #391
> [cd] 백엔드 개발 서버 젠킨스 배포파일에 소나큐브 설정 추가

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
내가 만든 카테고리 리스트를 검색한다.
Closes #380
> [feat] 내가 만든 카테고리 리스트를 검색한다.

- backend/src/main/java/com/allog/dallog/domain/externalcalendar/application/ExternalCalendarClient.java
- backend/src/main/java/com/allog/dallog/domain/externalcalendar/application/ExternalCalendarService.java
- backend/src/main/java/com/allog/dallog/domain/externalcalendar/dto/ExternalCalendarSchedule.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/dto/GoogleCalendarEventResponse.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/dto/GoogleCalendarEventsResponse.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/dto/GoogleDateFormat.java
- backend/src/test/java/com/allog/dallog/common/fixtures/ExternalCalendarFixtures.java
- backend/src/test/java/com/allog/dallog/infrastructure/oauth/client/StubExternalCalendarClient.java
구글 캘린더의 특정 캘린더 일정 리스트를 조회한다.
Closes #369
> [feat] 구글 캘린더의 특정 캘린더 일정 리스트를 조회한다.

- frontend/src/components/ScheduleAddButton/ScheduleAddButton.styles.ts
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/useSchedulePriority.ts
- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/StartPage/StartPage.styles.ts
시작 페이지 애니메이션 버그를 같이 수정했습니다.
Closes #388
> [feat] 달력 view를 수정한다.

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/RegisterService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponse.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/ScheduleResponse.java
- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepositoryTest.java
카테고리 삭제 시 연관된 스케줄도 삭제한다.
⚠️ entity에 기본 getter 외의 getter를 두지 말자.
Closes #392
> [fix] 카테고리 삭제 시 연관된 스케줄도 삭제한다.

- frontend/src/App.tsx
- frontend/src/components/@common/ErrorBoundary/ErrorBoundary.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/index.tsx
- frontend/src/pages/AuthPage/AuthPage.tsx
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/StartPage/StartPage.tsx
> [refactor] 에러 처리 로직을 리팩토링한다.

- backend/build.gradle
- jenkins/backend-dev.jenkinsfile
- 소나큐브 수행을 위해 `build.gradle` 파일 수정 
- 소나큐브 수행을 위해 `jenkins-dev` 파일 수정
Closes #412
> [feat] CD 시점에 백엔드 개발서버에 대한 소나큐브 정적 분석을 실행한다.

- frontend/src/App.tsx
- frontend/src/hooks/useUserValue.ts
- frontend/src/pages/NotFoundPage/NotFoundPage.styles.ts
- frontend/src/pages/NotFoundPage/NotFoundPage.tsx
> [feat] NotFound 페이지를 구현한다.

- frontend/src/components/@common/Fieldset/Fieldset.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/hooks/useControlledInput.ts
- frontend/src/hooks/useValidateSchedule.ts
- frontend/src/utils/date.ts
- 날짜 기본값에 시간 추가
- (시작 날짜와 종료 날짜가 같은 경우 대응)
- 시작 날짜 및 종료 날짜 검증 onChange -> onBlur
Closes #407
> [feat] 일정의 시작 날짜 및 종료 날짜를 자동으로 설정하는 기능을 구현한다.

- jenkins/frontend-dev.jenkinsfile
프론트엔드 개발 서버 배포 스크립트를 추가한다. 
Closes #419
> [ci] 프론트엔드 개발 서버 배포 스크립트를 추가한다. 

- jenkins/frontend-dev.jenkinsfile
> [ci] 프론트엔드 개발서버 배포 스크립트를 추가한다.

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/RegisterService.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- 개인 일정 -> 내 일정으로 이름 변경
- 내 일정 이름 수정 불가
- 내 일정 삭제 불가
Closes #398
> [feat] 내 일정 카테고리의 이름 수정이나 삭제가 불가능 하도록 한다.

- frontend/src/pages/NotFoundPage/NotFoundPage.styles.ts
- frontend/src/pages/NotFoundPage/NotFoundPage.tsx
> [style] NotFound 페이지 레이아웃을 수정한다.

- frontend/src/@types/index.ts
- frontend/src/@types/schedule.ts
- frontend/src/components/DateModal/DateModal.styles.ts
- frontend/src/components/DateModal/DateModal.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.styles.ts
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
- frontend/src/pages/CalendarPage/CalendarPage.tsx
모달에서 일정 클릭은 아직 되지 않습니다
to do!
달력 페이지에서 구조가 크게 달라지지 않도록 구현했습니다
근데 아무래도 추후에 정리하는 게 좋을 것 같아요 👀
Closes #425
> [feat] 날짜 단건 조회 모달 컴포넌트를 구현한다.

- frontend/src/@types/googleCalendar.ts
- frontend/src/App.tsx
- frontend/src/api/googleCalendar.ts
- frontend/src/components/GoogleImportModal/GoogleImportModal.styles.ts
- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/useControlledInput.ts
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
select도 제어 컴포넌트가 가능하다고 합니다!
Closes #396
> [feat] 구글 캘린더 일정 가져오기 기능을 구현한다.

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
- jenkins/frontend-dev.jenkinsfile
- jenkins/frontend-prod.jenkinsfile
- 프론트엔드 dev 서버 정상화
- 프론트엔드 prod 서버 정상화
- config 서브모듈 최신화 (프론트엔드 dev 서버를 백엔드 dev 서버 CORS 목록에 추가)
- config 서브모듈 최신화 (oauth redirect uri르 프론트엔드 dev 서버로 변경)
프론트엔드 prod 서버는 현재 main 브랜치에 아무 frontend 파일도 없어서 실패하는 것이 맞습니다!
Closes #435
> [ci] 프론트엔드 빌드 파이프라인을 정상화한다.

- .github/workflows/frontend-ci.yml
- frontend/package.json
프론트엔드 배포 script를 수정한다.
Closes #441
> [ci] 프론트엔드 배포 script를 수정한다.

- backend/src/docs/asciidoc/external-calendar.adoc
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
- backend/src/main/java/com/allog/dallog/domain/category/exception/DuplicatedExternalCategoryException.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/ExternalCalendarControllerTest.java
외부 캘린더가 중복 저장되지 않도록 한다.
Closes #418
> [feat] 외부 캘린더가 중복 저장되지 않도록 한다. 

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/auth/application/OAuthUri.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/GoogleOAuthUri.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java
RedirectURI를 프론트엔드에서 직접 받아 OAuth URI를 생성하도록 개선한다. 
Closes #446
> [feat] RedirectURI를 프론트엔드에서 직접 받아 OAuth URI를 생성하도록 개선한다. 

- backend/src/docs/asciidoc/auth.adoc
- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/auth/application/OAuthClient.java
- backend/src/main/java/com/allog/dallog/domain/auth/dto/request/TokenRequest.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
- backend/src/test/java/com/allog/dallog/common/fixtures/AuthFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/infrastructure/oauth/client/StubOAuthClient.java
- backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java
RedirectURI를 프론트엔드에서 직접 받아 Access Token을 발급받도록 개선한다.
Closes #446
> [feat] RedirectURI를 프론트엔드에서 직접 받아 Access Token을 발급받도록 개선한다.

- frontend/src/api/login.ts
> [fix] 로그인 요청을 수정한다.

- frontend/src/@types/category.ts
- frontend/src/api/category.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/constants/category.ts
- frontend/src/mocks/handlers.ts
카테고리 필드에 categoryType이 추가되었습니다~
Closes #453
> [feat] 카테고리 추가 시 categoryType을 설정한다.

- backend/src/main/java/com/allog/dallog/domain/externalcalendar/dto/ExternalCalendarSchedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleCreateRequest.java
제목 없는 일정도 받을 수 있게 수정한다.
Closes #454
> [fix] 제목 없는 일정도 받을 수 있게 수정한다.

- frontend/src/@types/schedule.ts
- frontend/src/api/schedule.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/mocks/data.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- 일정 수정 쪽 에러도 수정했습니다!
Closes #456
> [refactor] 일정의 id 타입을 변경한다. 

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
외부로 부터 연동한 카테고리도 삭제 가능하도록 변경
Closes #450
> [refactor] 외부로 부터 연동한 카테고리도 삭제 가능하도록 변경

- backend/src/main/java/com/allog/dallog/domain/category/dto/response/CategoryResponse.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
간단히 `CategoryResponse` 에 `categoryType` 을 string 타입으로 추가하였습니다.
Closes #464
> [feat] 카테고리 조회(단건, 전체 모두)시 CategoryType을 함께 보내주도록 변경한다.

- frontend/src/@types/schedule.ts
- frontend/src/api/schedule.ts
- frontend/src/components/MyCategoryItem/MyCategoryItem.style.ts
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.styles.ts
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/constants/message.ts
- frontend/src/mocks/data.ts
> [feat] 카테고리 타입에 따라 구독, 수정 등의 권한 부여를 설정한다.

- backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
불변의 emptyList로 인해 일정 추가가 불가능한 기능을 해결한다.
버그 재현은 #448 이슈에서 확인해주세요!
Closes #448
> [fix] 불변의 emptyList로 인해 일정 추가가 불가능한 기능을 해결한다.

- frontend/src/pages/CalendarPage/CalendarPage.tsx
- 겹치는 반복일정에서 일정 더보기가 나오지 않는 에러를 수정한다.
Closes #471
> [fix] 겹치는 반복일정에서 일정 더보기가 나오지 않는 에러를 수정한다.

- frontend/src/hooks/useSchedulePriority.ts
달력 뷰를 넘어가는 장기 일정의 렌더링 오류를 수정한다.
Closes #473
> [fix] 달력 뷰를 넘어가는 장기 일정의 렌더링 오류를 수정한다.

- frontend/src/components/ScheduleModal/ScheduleModal.tsx
일정 삭제 시 달력에 바로 반영되지 않는 에러를 수정한다.
Closes #475
> [fix] 일정 삭제 시 달력에 바로 반영되지 않는 에러를 수정한다.

- frontend/src/@types/subscription.ts
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.styles.ts
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
- frontend/src/components/MyCategoryItem/MyCategoryItem.style.ts
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.styles.ts
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
카테고리 타입에 따라 description을 보여준다.
Closes #477
> [feat] 카테고리 타입에 따라 description을 보여준다.

- frontend/src/@types/scheduler.ts
- frontend/src/App.tsx
- frontend/src/api/scheduler.ts
- frontend/src/components/@common/Fieldset/Fieldset.tsx
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
- frontend/src/components/MyCategoryList/MyCategoryList.tsx
- frontend/src/components/NavBar/NavBar.styles.ts
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/constants/api.ts
- frontend/src/constants/index.ts
- frontend/src/hooks/useUserValue.ts
- frontend/src/pages/AuthPage/AuthPage.tsx
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/SchedulingPage/SchedulingPage.styles.ts
- frontend/src/pages/SchedulingPage/SchedulingPage.tsx
- frontend/src/pages/StartPage/StartPage.tsx
디자인... 피드백 부탁드립니다... 😶‍🌫️
Closes #463
> [feat] 일정 조율 페이지 컴포넌트를 구현한다.

- frontend/src/hooks/useSchedulePriority.ts
https://github.com/woowacourse-teams/2022-dallog/issues/481
Closes #481
> [fix] 복수 일정의 우선순위 에러를 수정한다.

- frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx
구독 카테고리 필터링 후 로딩 시 스피너를 추가한다. 
Closes #483
> [feat] 구독 카테고리 필터링 후 로딩 시 스피너를 추가한다. 

- frontend/src/components/Profile/Profile.tsx
프로필 수정 후 카테고리 페이지의 생성자가 바로 변하지 않는 에러를 수정한다.
Closes #486
> [fix] 프로필 수정 후 카테고리 페이지의 생성자가 바로 변하지 않는 에러를 수정한다.

- frontend/src/components/@common/Fieldset/Fieldset.styles.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.styles.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/GoogleImportModal/GoogleImportModal.styles.ts
- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.styles.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
입력 필드의 label을 추가한다.
Closes #488
> [feat] 입력 필드의 label을 추가한다.

- frontend/src/components/DateModal/DateModal.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
일정 제목 비어있다면 "제목없음"으로 보여준다.
Closes #491
> [feat] 일정 제목 비어있다면 "제목없음"으로 보여준다.

- frontend/src/components/@common/Fieldset/Fieldset.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.styles.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
https://github.com/woowacourse-teams/2022-dallog/issues/494
Closes #494
> [feat] 일정 추가 시 카테고리 default 값을 설정한다.

- backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/SchedulerService.java
- backend/src/test/java/com/allog/dallog/domain/composition/application/CalendarServiceTest.java
일정 조율 기능을 외부 일정(구글 캘린더)도 조율 대상에 포함하도록 개선합니다.
Closes #466
> [feat] 일정 조율 기능을 외부 일정(구글 캘린더)도 조율 대상에 포함하도록 개선한다.

- backend/build.gradle
-[x] 소나큐브의 코드 커버리지 분석에 불필요한 파일을 제거한다.
Closes #498
> [cd] 소나큐브의 코드 커버리지를 높힌다.

- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
카테고리 페이지를 모드 선택을 토글로 변경한다.
Closes #497
> [style] 카테고리 페이지를 모드 선택을 토글로 변경한다.

- frontend/src/App.tsx
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/hooks/useUserValue.ts
- frontend/src/pages/NotFoundPage/NotFoundPage.tsx
- frontend/src/recoil/atoms/index.ts
- 전역 사이드 바 default 상태 true -> false
- access token 유효성 검사 성공 시 전역 사이드 바 상태 유지
Closes #492
> [fix] 페이지 이동 시 사이드 바가 열리는 에러를 수정한다.

- frontend/src/components/FilterCategoryList/FilterCategoryList.styles.ts
- frontend/src/components/FilterCategoryList/FilterCategoryList.tsx
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
> [style] 구글 캘린더 가져오기 버튼을 사이드 바로 옮긴다.

- frontend/src/hooks/useSchedulePriority.ts
특정 달에서 달력이 렌더링되지 않는 에러를 수정한다.
Closes #510
> [fix] 특정 달에서 달력이 렌더링되지 않는 에러를 수정한다.

- frontend/src/pages/CalendarPage/CalendarPage.tsx
다른 연도, 오늘 날짜에 today effect를 제거한다.
Closes #512
> [fix] 다른 연도, 오늘 날짜에 today effect를 제거한다.

- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
`Schedule`의 `title` 길이 제한을 50자로 변경
Closes #515
> [refactor] 일정제목 글자수 제한을 50자로 변경한다.

- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
이슈와 다르게 추가적으로 수정한 부분들이 많이 있어요!
Closes #513
> [feat] 일정 렌더링을 수정한다.

- frontend/src/App.tsx
- frontend/src/components/@common/ErrorBoundary/ErrorBoundary.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/SnackBar/SnackBar.styles.ts
> [refactor] 에러 처리 컴포넌트에서 스낵바 기능을 분리한다.

- backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthToken.java
외부 리소스에 대한 null 처리를 추가한다.
1. 재로그인 시 refreshToken이 null이 들어온다.
2. 이것을 change하면 null 제약 조건으로 인해 예외가 발생한다.
Closes #526
> [fix] 외부 리소스에 대한 null 처리를 추가한다.

- README.md
> [docs] Readme를 작성한다.

- README.md
- stortbook -> storybook
- 기술 스택 추가
Closes #533
> [docs] README 기술스택의 오타를 수정하고 새로운 기술을 추가한다.

- backend/src/main/java/com/allog/dallog/global/config/properties/GoogleProperties.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/DevGoogleOAuthUri.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/common/config/ExternalApiConfig.java
- backend/src/test/java/com/allog/dallog/domain/integrationschedule/dao/IntegrationScheduleDaoTest.java
- backend/src/test/java/com/allog/dallog/infrastructure/oauth/uri/StubOAuthUri.java
- backend/src/test/resources/application.yml
서브모듈이 변경 되었습니다! merge되면 최신화 해주시면 감사하겠습니다!
Closes #535
> [feat] 개발 전용 구글 애플리케이션 생성 및 적용한다.

- .github/workflows/frontend-ci.yml
- frontend/.eslintrc.json
- frontend/public/mockServiceWorker.js
- frontend/src/@types/emotion.d.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/yarn.lock
일정 추가 모달에서 카테고리 select 요소를 아래쪽으로 옮긴다.
카테고리 선택창을 아래로 옮기니 뭔가 어색하게 느껴져서 일정과 카테고리를 구분하는 선을 넣었습니다.
~~지금도... 어색해 보이긴 해요 🥲~~
이에 대한 피드백 부탁드릴게요!
아래 캡쳐본으로 수정하였습니다
Closes #544
> 일정 추가 모달에서 카테고리 select 요소를 아래쪽으로 옮긴다.

- frontend/src/hooks/useUserValue.ts
> [fix] 구글 캘린더 구독 및 색상 변경 시 발생하는 에러를 해결한다.

- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
카테고리 페이지에서 나의 카테고리 목록을 제거한다.
Closes #545
> [feat] 카테고리 페이지에서 나의 카테고리 목록을 제거한다.

- frontend/src/api/profile.ts
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/WithdrawalModal/WithdrawalModal.stories.tsx
- frontend/src/components/WithdrawalModal/WithdrawalModal.styles.ts
- frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
- frontend/src/constants/message.ts
- frontend/src/constants/validate.ts
- frontend/src/validation/index.ts
> [feat]회원 탈퇴 기능을 구현한다.

- .github/workflows/backend-ci.yml
- publish-unit-test-result-action workflow가 올바르게 동작하도록 수정합니다.
- jacoco-report 를 사용하여 변경된 파일에 대해 코드 커버리지를 PR 코멘트로 출력합니다.
Closes #561
> [ci] publish-unit-test-result-action workflow가 올바르게 동작하도록 수정한다.

- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.styles.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
1. 미션... 이후로 아이콘을 최대한 사용하지 않는 게 성능에 좋을 거라고 판단하여 아이콘을 사용하지 않았습니다.
2. Fieldset 공통 컴포넌트와 다른 부분이 많아 이를 사용하지 않았습니다.
3. `accent-color` 속성을 사용해서 체크박스를 디자인하니 `YELLOW_500` 색상을 사용하는 경우에 체크가 회색으로 보이더라고요. 그래서 체크가 흰색으로 보이는 `ORANGE_500` 색상을 사용하였습니다. -> 예뻐 보이진 않아요 🥲 체크박스 디자인에 대한 피드백 부탁드립니다!
Closes #542
> [feat] 종일 버튼을 개선한다.

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/main/java/com/allog/dallog/domain/subscription/dto/response/SubscriptionResponse.java
- backend/src/main/java/com/allog/dallog/presentation/SubscriptionController.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepositoryTest.java
- backend/src/test/java/com/allog/dallog/presentation/SubscriptionControllerTest.java
- Subscription과 관련한 전체 객체(`Controller`, `Service`, `Entity`)를 리팩터링
Closes #581
> [refactor] 구독과 관련한 ServiceLayer의 구조를 개선한다.

- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
- backend/src/main/java/com/allog/dallog/domain/subscription/dto/response/SubscriptionResponse.java
- backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java
- 일정과 관련한 객체(Service, Controller, Repository, Entity)전체 수정
Closes #585
> [refactor] 일정과 관련한 ServiceLayer의 구조를 개선한다. 

- .github/workflows/backend-ci.yml
Github actions 테스트 커버리지 표시 플러그인을 제거한다.
Closes #593
> [ci] Github actions 테스트 커버리지 표시 플러그인을 제거한다.

- backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
쿼리 분석 중 application 계층의 메서드에 누락된 테스트를 추가한다.
Closes #596
> [test] 쿼리 분석 중 application 계층의 메서드에 누락된 테스트를 추가한다.

- frontend/src/App.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/hooks/useControlledInput.ts
- frontend/src/hooks/useUserValue.ts
[react query stale time 변경](https://github.com/woowacourse-teams/2022-dallog/commit/9f52e53d86904b769f8dc6ee36b20f522a5d6883)
stale time을 1분으로 설정하여 api 요청 횟수를 줄일 수 있도록 하였습니다.
`refetchOnWindowFocus` 옵션은 사용자가 오랫동안 창을 벗어나 있을 경우에 대비하여 default인 true로 두는 게 좋다고 생각했어요~!
Closes #586
> [perf] react query 설정을 변경한다.

- frontend/src/components/@common/Fieldset/Fieldset.tsx
- frontend/src/components/@common/Select/Select.stories.tsx
- frontend/src/components/@common/Select/Select.styles.ts
- frontend/src/components/@common/Select/Select.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.styles.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/constants/date.ts
- frontend/src/constants/style.ts
- frontend/src/hooks/useValidateSchedule.ts
- frontend/src/pages/SchedulingPage/SchedulingPage.tsx
- frontend/src/utils/date.ts
- Select 컴포넌트가 Fieldset 컴포넌트처럼 커스텀한 cssProp이 없습니다. (고정된 스타일링) -> 추후 수정 예정
Closes #567
> [feat] Date Time Picker 기능을 구현한다.

- backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
- backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
- backend/src/main/java/com/allog/dallog/domain/externalcalendar/application/ExternalCalendarService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
> [fix] OAuthAccessTokenResponse이 정상적으로 맵핑되지 않는 문제를 해결한다.

- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/constants/date.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/utils/date.ts
호호... 리팩토링이 시급합니다 🚨
리팩토링도 함께 하려고 했는데 나인이랑 같이 하는 게 좋을 것 같아서 하지 않았어요~!
크리티컬하게 리팩토링이 필요한 부분이라면 알려주세요 🫠
Closes #620
> [fix] 종일 일정의 종료 시각을 다음 날 00:00으로 변경한다.

- frontend/src/@types/index.ts
- frontend/src/components/@common/Select/Select.styles.ts
- frontend/src/components/@common/Select/Select.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.styles.ts
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.styles.ts
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
일정 수정 시 카테고리도 수정할 수 있도록 변경한다.
- 아직 백엔드 쪽 API 관련 PR이 merge 되지 않아서 실제 기능을 동작하지 않습니다.
- `Fieldset` 컴포넌트처럼 `Select` 컴포넌트에도 `cssProp`을 주어 커스텀할 수 있도록 했습니다.
Closes #604
> [feat] 일정 수정 시 카테고리도 수정할 수 있도록 변경한다.

- frontend/src/App.tsx
> [fix] 라우팅 에러를 수정한다.

- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/constants/date.ts
- frontend/src/utils/date.ts
> [fix] 일정 수정 시 종일을 파악하지 못하는 에러를 해결한다.

- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
일정 수정 시 여러 일에 걸친 일정에 대해 날짜 입력 필드가 제대로 동작하지 않는 에러를 해결한다.
Closes #645
> [fix] 일정 수정 시 여러 일에 걸친 일정에 대해 날짜 입력 필드가 제대로 동작하지 않는 에러를 해결한다.

- frontend/src/components/SideBar/SideBar.tsx
> [perf] http 요청 수를 줄인다.

- backend/src/main/resources/application-test.yml
- backend/src/main/resources/logback-spring.xml
개발 환경에서 MySQL 데이터베이스를 활용하도록 수정한다.
그 밖에도 로깅 관련하여 디버깅하기 용이하도록 수정하였습니다. 
서브모듈이 변경 되었습니다! 확인해주십쇼
Closes #644
> [refactor] 개발 환경에서 MySQL 데이터베이스를 활용하도록 수정한다.

- frontend/src/index.html
- frontend/src/styles/GlobalStyle.tsx
> [perf] TTI(Time To Interactive)를 개선한다.

- frontend/src/pages/StartPage/StartPage.styles.ts
> [perf] layout shift를 제거한다.

- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
종일 체크박스를 제어 컴포넌트에서 제외 대상을 선정한다.
Closes #659
> [fix] 종일 체크박스를 제어 컴포넌트에서 제외 대상을 선정한다.

- frontend/src/App.tsx
- frontend/src/hooks/useUserValue.ts
- stale time 전역 설정 제거
Closes #663
> [hotfix] react query stale time 설정으로 인한 정보 업데이트 지연을 해결한다.

- frontend/src/api/schedule.ts
- frontend/src/components/MoreScheduleModal/MoreScheduleModal.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/components/SideItem/SideItem.tsx
- frontend/src/constants/index.ts
- frontend/src/constants/style.ts
- frontend/src/hooks/useCalendar.ts
- frontend/src/hooks/useModalPosition.ts
- frontend/src/hooks/useSchedulePriority.ts
- frontend/src/hooks/useValidateSchedule.ts
- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/utils/date.ts
> [refactor] CalendarPage를 리팩토링한다.

- frontend/src/hooks/@queries/login.ts
- frontend/src/hooks/useUserValue.ts
- frontend/src/pages/AuthPage/AuthPage.tsx
- frontend/src/pages/StartPage/StartPage.tsx
커스텀훅 분리 코멘틀 받기 위해 로그인 부분만 커스텀훅으로 변경하고 먼저 올립니다 티거😝😝
Closes #699
> [refactor] 로그인 관련 query를 커스텀훅으로 분리한다.

- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/components/SideItem/SideItem.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/hooks/@queries/schedule.ts
- frontend/src/hooks/@queries/subscription.ts
구독 관련 query를 커스텀훅으로 분리한다.
Closes #702
> [refactor] 구독 관련 query를 커스텀훅으로 분리한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/auth/application/JwtTokenProvider.java
- backend/src/main/java/com/allog/dallog/domain/auth/application/TokenProvider.java
- backend/src/main/resources/application-test.yml
- backend/src/test/java/com/allog/dallog/common/config/TokenConfig.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/JwtTokenProviderTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/StubTokenProvider.java
- RefreshToken의 만료시간을 2주로 변경하고 JWT로 암호화한다.
서브모듈에 refreshToken에 대한 설정이 추가되어 서브모듈이 변경되었습니다!
`git submodule update --init`을 통해 최신화를 맞춰야 할것 같아요!
Closes #686
> [refactor] RefreshToken의 만료시간을 2주로 변경한다.

- backend/src/docs/asciidoc/category.adoc
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/category/dto/response/CategoryDetailResponse.java
- backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
- backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
카테고리 단 건 조회 시 구독자수를 포함하여 반환한다.
Closes #707
> [feat] 카테고리 단 건 조회 시 구독자수를 포함하여 반환한다.

- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
우선 순위가 낮은 카테고리 노출 방지를 위한 카테고리 리스트 정렬을 개선한다. (구독자 or 업데이트)
#708 merge 이후 순차적으로 진행하겠습니다!
Closes #670
> [refactor] 우선 순위가 낮은 카테고리 노출 방지를 위한 카테고리 리스트 정렬을 개선한다.

- frontend/src/api/category.ts
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.styles.ts
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.styles.ts
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/pages/CalendarPage/CalendarPage.styles.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
캘린더를 얼른 분리하고 싶어요 🥲
반응형도 얼른 대응하고 싶어요 🥲
Closes #675
> [feat] 카테고리 조회 페이지를 변경한다.

- frontend/src/@types/category.ts
- frontend/src/api/category.ts
- frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
- frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
- frontend/src/constants/api.ts
- frontend/src/hooks/@queries/category.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
카테고리 관련 api를 커스텀훅으로 변경한다.
Closes #728
> [refactor] 카테고리 관련 api를 커스텀훅으로 변경한다.

- frontend/src/components/GoogleImportModal/GoogleImportModal.tsx
- frontend/src/hooks/@queries/googleCalendar.ts
> [refactor] 구글 캘린더 관련 query를 커스텀 훅으로 분리한다.

- frontend/src/components/SubscriptionModifyModal/SubscriptionModifyModal.tsx
사이드바에서도 구독 카테고리의 구독 해제를 진행할 수 있다.
Closes #740
> [feat] 사이드바에서도 구독 카테고리의 구독 해제를 진행할 수 있다.

- backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- 회원 탈퇴 로직 수행 시, category와 categoryRole의 삭제 순서를 변경
Closes #751
> [bug] 회원탈퇴가 안되는 이슈를 해결한다.

- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- 회원 탈퇴시, 내 카테고리를 구독한 사람들의 구독 정보, 카테고리 권한을 제거한다.
Closes #751
> [bug] 회원탈퇴가 안되는 이슈를 추가로 해결한다.

- frontend/src/hooks/useSchedulePriority.ts
복수 일정이 달력에 제대로 렌더링 되지 않는 에러를 해결한다.
Closes #759
> [fix] 복수 일정이 달력에 제대로 렌더링 되지 않는 에러를 해결한다.

- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
- backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- 회원 탈퇴 시 회원의 카테고리 권한과 연관된 데이터를 모두 삭제한다.
Closes #667
> [bug] 회원 탈퇴 시 발생하는 서버 에러를 해결한다. 

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
회원가입시 내 일정 카테고리에 대한 CategoryRole을 추가하도록 개선함
Closes #765
> [bug] 회원가입시 '내 일정' 카테고리가 일정 추가 대상 카테고리에 보이지 않는다.

- backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
- backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
- backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- 회원 탈퇴 로직에 분기 처리를 한다.
Closes #751
> [bug] 회원 탈퇴 로직을 변경한다.

- frontend/src/@types/category.ts
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.styles.ts
- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.styles.ts
- frontend/src/components/UnsubscribedCategoryItem/UnsubscribedCategoryItem.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/@queries/category.ts
- frontend/src/hooks/useHoverCategoryItem.ts
> [feat] 카테고리 단건 조회 기능을 구현한다.

- frontend/src/components/Profile/Profile.tsx
- frontend/src/hooks/@queries/category.ts
회원 탈퇴 버튼을 제거한다. (임시)
Closes #778
> [feat] 회원 탈퇴 버튼을 제거한다. (임시)

- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/test/java/com/allog/dallog/domain/member/domain/MemberTest.java
회원가입 시 nickname의 글자 제한을 늘린다.
Closes #788
> [fix] 회원가입 시 nickname의 글자 제한을 늘린다.

- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
`NotAbleToUnsubscribeException` 이 ControllerAdvice 에서 누락되어 있었네요! 추가했습니다.
Closes #809
> [fix] 내가 유일한 ADMIN인 카테고리를 카테고리 페이지에서 구독해제시 발생하는 에러를 수정한다.

- frontend/src/components/SideAdminList/SideAdminList.styles.ts
- frontend/src/components/SideAdminList/SideAdminList.tsx
- frontend/src/components/SideGoogleList/SideGoogleList.styles.ts
- frontend/src/components/SideGoogleList/SideGoogleList.tsx
- frontend/src/components/SideItem/SideItem.styles.ts
- frontend/src/components/SideSubscribedList/SideSubscribedList.styles.ts
- frontend/src/components/SideSubscribedList/SideSubscribedList.tsx
사이드 바에서 구독 카테고리 목록이 잘리는 에러를 해결한다.
Closes #795
Closes #796
> [fix] 사이드 바에서 구독 카테고리 목록이 잘리는 에러를 해결한다.

- frontend/src/components/MoreScheduleModal/MoreScheduleModal.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/CategoryPage/CategoryPage.tsx
띄어쓰기만 있는 일정 제목을 (제목없음)으로 표시한다.
Closes #806
> [fix] 띄어쓰기만 있는 일정 제목을 (제목없음)으로 표시한다.

- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/components/ScheduleAddButton/ScheduleAddButton.tsx
- frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
- frontend/src/components/SideBar/SideBar.tsx
- frontend/src/pages/CalendarPage/CalendarPage.tsx
> [feat] 달록의 웹접근성을 개선한다.

- jenkins/frontend-dev.jenkinsfile
jenkins 빌드 명령어를 수정한다.
Closes #831
> [fix] jenkins 빌드 명령어를 수정한다.

- frontend/package.json
- frontend/tsconfig.json
- frontend/webpack.config.js
- frontend/yarn.lock
- CleanWebpackPlugin 제거
- devtool 변경
- resolve extensions 불필요한 확장자 제거
- loader 적용 방식 변경
- contenthash 적용
- tsconfig jsx 변경
Closes #829
> [chore] webpack 설정 및 typescript 컴파일 전략을 세운다.

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
- 젠킨스 스크립트에 무중단 배포 적용
- 스프링 실행 스크립트 포트 번호 변수로 받아 설정하도록 수정
- Nginx default.conf 파일 수정
- prod 배포 시 무중단 배포가 잘 되는지 확인 필요
Closes #790
> [feat] 무중단 배포를 구현한다.

- backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryUpdateRequest.java
- backend/src/main/java/com/allog/dallog/domain/category/dto/request/ExternalCategoryCreateRequest.java
- backend/src/main/java/com/allog/dallog/domain/member/dto/request/MemberUpdateRequest.java
- backend/src/main/java/com/allog/dallog/domain/subscription/dto/request/SubscriptionUpdateRequest.java
- backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
- backend/src/main/java/com/allog/dallog/presentation/ExternalCalendarController.java
- backend/src/main/java/com/allog/dallog/presentation/MemberController.java
- backend/src/main/java/com/allog/dallog/presentation/SubscriptionController.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
- 전체 Controller 객체의 검증이 필요한 파라미터의 `@Valid` 애노테이션 추가
Closes #825
> [refactor] 전체 기능의 Dto 검증을 위한 애노테이션을 컨트롤러에 추가한다.

- frontend/src/App.tsx
- frontend/src/components/@common/ErrorBoundary/ErrorBoundary.tsx
- frontend/src/pages/ErrorPage/ErrorPage.styles.ts
- frontend/src/pages/ErrorPage/ErrorPage.tsx
- frontend/src/pages/NotFoundPage/NotFoundPage.tsx
에러 바운더리 페이지를 구현한다.
일단은~ NotFoundPage처럼 구현했어요!
Closes #785
> [feat] 에러 바운더리 페이지를 구현한다.

- frontend/src/components/SnackBar/SnackBar.styles.ts
- frontend/src/components/SnackBar/SnackBar.tsx
스낵바 메세지가 남아있는 에러를 해결한다.
Closes #843
> [fix] 스낵바 메세지가 남아있는 에러를 해결한다.

- frontend/src/App.tsx
Lazy Import를 적절하게 적용한다.
Closes #793
> [refactor] Lazy Import를 적절하게 적용한다.

- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
> [feat] 카테고리 페이지를 개선한다.

- frontend/src/@types/category.ts
- frontend/src/api/category.ts
- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/CategoryList/CategoryList.tsx
- frontend/src/hooks/@queries/category.ts
카테고리 목록을 한 번에 불러오도록 변경한다.
Closes #854
> [refactor] 카테고리 목록을 한 번에 불러오도록 변경한다.

- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
> [style] 검색 버튼을 보이게 한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
- backend/src/main/java/com/allog/dallog/domain/externalcalendar/application/ExternalCalendarService.java
- backend/src/main/java/com/allog/dallog/domain/schedule/application/CheckedSchedulesFinder.java
- backend/src/main/java/com/allog/dallog/presentation/auth/AuthController.java
- backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/application/ExternalCategoryDetailServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/CheckedSchedulesFinderTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java
외부 리소스 요청을 트랜잭션 내에서 분리한다.
Closes #719
> [refactor] 외부 리소스 요청을 트랜잭션 내에서 분리한다.

- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
https://github.com/woowacourse-teams/2022-dallog/issues/857
Closes #857
> [fix] 카테고리 목록 리스트 길이가 변하는 에러를 해결한다.

- frontend/src/App.tsx
- frontend/src/components/Profile/Profile.tsx
- frontend/src/constants/api.ts
- frontend/src/constants/message.ts
- frontend/src/hooks/@queries/login.ts
- frontend/src/index.tsx
401 발생 시 자동 로그인이 되도록 한다.
Closes #868
> [feat] 401 발생 시 자동 로그인이 되도록 한다.

- frontend/src/pages/CalendarPage/CalendarPage.tsx
일정이 10개 이상 쌓이면 일정 더보기가 나오지 않는 에러를 해결한다.
Closes #807
> [fix] 일정이 10개 이상 쌓이면 일정 더보기가 나오지 않는 에러를 해결한다.

- jenkins/backend-dev.jenkinsfile
- jenkins/backend-prod.jenkinsfile
- jenkins/frontend-dev.jenkinsfile
- jenkins/frontend-prod.jenkinsfile
2개의 인스턴스를 추가로 만들어 각각의 agent가 backend, frontend 빌드 및 배포를 담당하여 부하를 분산하도록 개선
Closes #872
> [feat] 젠킨스 분산 빌드 환경을 구축한다.

- backend/src/main/java/com/allog/dallog/domain/auth/application/JwtTokenProvider.java
- backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
- backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
- backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
- backend/src/main/java/com/allog/dallog/domain/member/domain/Member.java
- backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
- backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/DateRangeRequest.java
- backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleOAuthClient.java
- backend/src/main/java/com/allog/dallog/infrastructure/oauth/exception/OAuthException.java
- backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/auth/application/StubTokenProvider.java
- backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/application/ExternalCategoryDetailServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
- backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
- backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/CheckedSchedulesFinderTest.java
- backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
- backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
- Member -> `회원`으로 용어 통일 
- 예외 메시지 수정
- 불필요한 todo 삭제
Closes #853
> [refactor] 용어를 통일하고 예외 메시지를 수정한다. 

- frontend/src/components/ScheduleModal/ScheduleModal.styles.ts
- frontend/src/components/ScheduleModal/ScheduleModal.tsx
일정 상세 모달에서 메모가 넘쳐흐르는 에러를 해결한다.
Closes #876
> [fix] 일정 상세 모달에서 메모가 넘쳐흐르는 에러를 해결한다.

- frontend/src/hooks/@queries/category.ts
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.tsx
카테고리 페이지 달력에서 다른 달 미리보기가 되지 않는 에러를 해결한다.
Closes #875
> [fix] 카테고리 페이지 달력에서 다른 달 미리보기가 되지 않는 에러를 해결한다.

- frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.styles.ts
- frontend/src/pages/CategoryPage/CategoryPage.styles.ts
> [fix] UI 에러를 수정한다.

- frontend/src/hooks/useValidateSchedule.ts
일정 생성 시 발생하는 에러를 해결한다.
Closes #882
> [fix] 일정 생성 시 발생하는 에러를 해결한다.

- frontend/src/components/CategoryList/CategoryList.styles.ts
- frontend/src/components/SideBar/SideBar.styles.ts
- frontend/src/styles/GlobalStyle.tsx
> [style] 사이드바의 스크롤바를 호버했을때 나오도록 수정한다.

- frontend/src/components/SideAdminList/SideAdminList.tsx
- frontend/src/components/SideGoogleList/SideGoogleList.tsx
- frontend/src/components/SideItem/SideItem.tsx
- frontend/src/components/SideSubscribedList/SideSubscribedList.tsx
- frontend/src/components/SubscriptionModifyModal/SubscriptionModifyModal.tsx
- frontend/src/hooks/useRootFontSize.ts
- frontend/src/pages/CalendarPage/CalendarPage.tsx
- frontend/src/pages/CategoryPage/CategoryPage.tsx
- frontend/src/utils/index.ts
https://user-images.githubusercontent.com/32920566/197933889-ab456fee-781f-4cc5-a508-bd89bedcc95c.mp4
Closes #888
> [feat] 화면 resize 이벤트에 따라 반응형을 재조정한다.

- frontend/src/components/MoreScheduleModal/MoreScheduleModal.tsx
일정 더보기 모달 컴포넌트에서는 단순히 에러만 해결하였습니다
여기에 아주 간단한 리팩토링만 더했어요!
따라서 #893 보다 이 PR을 먼저 머지하겠습니다 🚨
Closes #895
> [fix] 일정 더보기 모달 에러를 해결한다.

- frontend/babel.config.js
- frontend/package.json
- frontend/yarn.lock
> [chore] Webpack 설정을 다시 점검하고 수정한다.

- frontend/babel.config.js
> [fix] 오타를 수정한다.

- backend/src/main/java/com/allog/dallog/categoryrole/domain/CategoryRoleRepository.java
- backend/src/test/java/com/allog/dallog/common/Constants.java
- backend/src/test/java/com/allog/dallog/schedule/application/ScheduleServiceTest.java
- backend/src/test/java/com/allog/dallog/subscription/application/SubscriptionServiceTest.java
- Schedule에 대한 통합테스트를 문장형테스트로 변경
- Subscription에 대한 통합테스트를 문장형테스트로 변경
Closes #916
> [refactor] Schedule과 Subscription 도메인에 대한 통합테스트를 문장형테스트로 변경한다.
