woowacourse-teams/2022-dallog

backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
backend/src/main/java/com/allog/dallog/category/domain/Category.java
backend/src/main/java/com/allog/dallog/category/dto/request/CategoryCreateRequest.java
backend/src/main/java/com/allog/dallog/category/dto/response/CategoryResponse.java
backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
backend/src/main/java/com/allog/dallog/member/service/MemberService.java
backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
backend/src/test/java/com/allog/dallog/category/domain/CategoryTest.java
backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
backend/src/test/java/com/allog/dallog/member/service/MemberServiceTest.java
backend/src/test/java/com/allog/dallog/subscription/service/SubscriptionServiceTest.java

- 카테고리 엔티티에 카테고리 생성한 유저 필드 추가
- 카테고리 생성시 유저 정보 저장하도록 수정
- 테스트 수정
Closes #95

[refactor] 카테고리 엔티티와 기존의 생성기능을 수정한다. 

---

backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java

`ControllerAdvice`에 `HttpMessageNotReadableException`의 핸들러를 추가하였습니다.
> 참고: https://docs.spring.io/spring-framework/docs/3.0.6.RELEASE_to_3.1.0.BUILD-SNAPSHOT/3.1.0.BUILD-SNAPSHOT/org/springframework/http/converter/HttpMessageConverter.html
Closes #176

[feat] Request Body를 생략하고 요청하면 Internal Server Error가 발생하는 버그를 해결한다.

---

frontend/src/api/category.ts
frontend/src/components/CategoryAddModal/CategoryAddModal.tsx
frontend/src/components/CategoryModifyModal/CategoryModifyModal.styles.ts
frontend/src/components/CategoryModifyModal/CategoryModifyModal.tsx
frontend/src/components/MyCategoryItem/MyCategoryItem.tsx
frontend/src/mocks/handlers.ts

`frontend/src/mocks/data.ts`의 `categoryDB`와 `myCategoryDB`를 각각 따로 관리하고 있습니다
Closes #84

[feat] 유저별 생성 카테고리 수정 기능을 구현한다.

---

backend/src/docs/asciidoc/schedule.adoc
backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleCreateRequest.java
backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/fixtures/ScheduleAcceptanceFixtures.java
backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/presentation/ScheduleControllerTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java

- 일정 추가 기능이 카테고리를 추가로 전달 받도록 개선
- 이에 따른 테스트코드 대거 수정
- Path Variable 에 전달된 데이터가 타입이 잘못되었을 경우 Controller Advice에서 400을 던지도록 개선 (MethodArgumentTypeMismatchException 예외)
- NoPermissionException 발생 시 401이 아닌 403을 던지도록 개선
Closes #205

[feat] 일정 추가 기능을 수정한다.

---

jenkins/backend-dev.jenkinsfile
jenkins/backend-prod.jenkinsfile
jenkins/frontend-prod.jenkinsfile

젠킨스의 **Pipeline script from SCM** 기능을 활용하면, 파이프라인 스크립트를 Git 저장소에 올리고 형상관리를 할 수 있게됩니다. 이 기능을 활용하기 위해 `jenkins` 라는 디렉토리를 가장 상위에 만들고, 젠킨스 job 별로 파이프라인 스크립트를 추가하였습니다. 민감한 정보 (Private IP 등)은 추가로 젠킨스의 환경변수로 분리했습니다. 젠킨스 시스템 설정을 참고해주세요.
- 현재 젠킨스 세팅을 파이프라인을 Git에서 가져오도록 변경해둔 상태로 이 PR이 머지되기 전까지는 빌드가 실패할 것 입니다.
- 현재는 `dev`, `prod` 모두 `develop` 브랜치에서 파이프라인 스크립트를 가져오도록 설정해두었습니다. `prod`의 경우 `main` 브랜치에서 파이프라인 스크립트를 가져와야겠지만, 아직 배포에 대한 정확한 논의가 되지 않았으므로 유보해두었습니다.
Closes #267

[ci] 젠킨스 파이프라인 스크립트를 형상관리할 수 있도록 개선한다. 

---

backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java

`Category`에 `Subscription` 에 대한 매핑을 추가하고, `orphanRemoval = true`를 추가하여, 카테고리 제거시 관련된 구독도 모두 제거되도록 개선하였습니다.
Closes #252

[fix] 구독 정보가 있는 카테고리 삭제가 되지 않는 이슈를 해결한다.

---

backend/src/main/resources/logback-spring.xml

실행 환경에 따른 로깅 전략을 설정한다.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
<include resource="org/springframework/boot/logging/logback/defaults.xml"/> // 1
<include resource="org/springframework/boot/logging/logback/console-appender.xml"/> // 2
<property name="LOG_PATH" value="./logs"/> // 3
<property name="LOG_FILE" value="${LOG_PATH}/dallog-%d{yyyy-MM-dd}-%i.log"/> // 4
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender"> // 5
<encoder>
<pattern>${FILE_LOG_PATTERN}</pattern>
</encoder>
<file>${LOG_PATH}/dallog.log</file>
<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
<fileNamePattern>${LOG_FILE}</fileNamePattern>
<maxFileSize>10MB</maxFileSize>
<maxHistory>10</maxHistory>
<totalSizeCap>100MB</totalSizeCap> …
```

[feat] 실행 환경에 따른 로깅 전략을 설정한다.

---

backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryCreateRequest.java
backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryUpdateRequest.java
backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleCreateRequest.java
backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/ScheduleUpdateRequest.java
backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java

DTO의 필드의 유효성 검증 (@NotBlank 등)을 통과하지 못할경우 Internal Server Error가 발생하는 문제를 해결합니다. 500 대신 400 Bad Request 를 반환하며, 에러가 발생한 필드와 원인에 대해 메시지를 함께 반환합니다.
Closes #177

[fix] DTO의 필드의 유효성 검증을 통과하지 못할경우 Internal Server Error가 발생하는 버그를 해결한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java

ScheduleService의 save 메소드가 ID대신 Response DTO를 반환하도록 개선하였습니다. 
Closes #227

[refactor] ScheduleService의 save 메소드가 Response DTO를 반환하도록 개선한다. 

---

backend/src/main/java/com/allog/dallog/domain/subscription/domain/Color.java
backend/src/main/resources/data.sql
backend/src/test/java/com/allog/dallog/domain/subscription/domain/ColorTest.java

- 프론트에서 받은 컬러 코드를 대소문자 구분없이 찾을 수 있도록 수정
- data.sql에 수정된 컬러 코드 반영
Closes #371

[fix] 컬러 코드 대소문자 에러를 해결한다.

---

backend/src/main/resources/data.sql

DB에 color enum 이름을 저장하도록 data.sql을 변경한다. 
Closes #376

[fix] DB에 color enum 이름을 저장하도록 data.sql을 변경한다. 

---

backend/build.gradle

백엔드 코드 커버러지가 일정 수준 이하라면 빌드가 실패하도록 Jacoco를 설정했습니다.
`DallogApplication`, 예외 객체, DTO 등은 커버리지 체크 대상에서 제외하였습니다. 
이 PR이 병합된 이후 개별 클래스의 라인 커버리지가 75% 이하로 떨어지면 빌드가 실패합니다. 자세한 내용은 코멘트로 달아두겠습니다.
Closes #401

[ci] 백엔드 코드 커버러지가 일정 수준 이하라면 빌드가 실패하도록 Jacoco를 설정한다.

---

backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryCreateRequest.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTypeTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java

- 외부 연동 카테고리에는 일반 일정을 등록할 수 없도록 막는다.
- 외부 연동 카테고리를 전체 조회 목록에서 제외시킨다.
Closes #429

[fix] 외부 연동 카테고리는 일반 일정을 등록하거나 전체 조회할 수 없다. 

---

jenkins/frontend-dev.jenkinsfile
jenkins/frontend-prod.jenkinsfile

젠킨스에서 프론트엔드 프로젝트 빌드시 npm 대신 yarn 을 사용하도록 변경합니다.
Closes #443

[ci] 젠킨스에서 프론트엔드 프로젝트 빌드시 npm 대신 yarn 을 사용하도록 변경한다.

---

backend/src/docs/asciidoc/subscription.adoc
backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/IntegrationSchedule.java
backend/src/test/java/com/allog/dallog/domain/composition/application/CalendarServiceTest.java
backend/src/test/java/com/allog/dallog/presentation/SubscriptionControllerTest.java

일정 조율 기능을 외부 일정(구글 캘린더)도 조율 대상에 포함하도록 개선했습니다. `CalendarService` 를 조금 수정했어요. 나중에 몰아서 리팩토링 해야할 것 같아요.
그리고 외부 일정 테스트는 모킹말고는 답이 없을 것 같아서 테스트 코드를 작성하지 못했어요. 내일 QA때 빡빡하게 돌려봐야 할 것 같습니다. 
Closes #466

[feat] 일정 조율 기능을 외부 일정(구글 캘린더)도 조율 대상에 포함하도록 개선한다.

---

backend/src/main/java/com/allog/dallog/global/config/properties/GoogleProperties.java
backend/src/main/java/com/allog/dallog/infrastructure/oauth/uri/GoogleOAuthUri.java

google OAuth 인증 요청을 위한 uri 생성 시 매 로그인시 마다 동의를 요청하지 않도록 prompt 설정을 제거한다.
* local 및 dev 환경에서 테스트할 때 refresh token을 발급 받지 못할 수 있습니다. 관련하여 이야기 나눈 뒤 해당 PR 반영하겠습니다.
* 서브모듈이 수정되었습니다. merge가 될 경우 서브모듈을 적절히 최신화 시켜야 합니다. 
Closes #518

구글 OAuth 요청 uri 생성 시 prompt 설정을 제거한다.

---

frontend/src/components/FilterCategoryItem/FilterCategoryItem.tsx

- handleClickFilledCheckbox, handleClickBlankCheckBox와 handleClickCategoryName 의 로직이 조금 겹친다는 느낌이 드네요. 어떻게 생각하시나요!
Closes #538

[feat] 스피너 위치 이동 및 카테고리 이름 클릭 시 check 설정 추가

---

backend/build.gradle

소나큐브 Ruleset을 달록 컨벤션에 맞게 수정합니다. 기존에 달록은 Sonar way라는 기본 제공 ruleset을 사용했습니다. 이것을 복제하고, 저희 프로젝트에 맞지 않는 규칙은 비활성화 시켰습니다. 비활성화한 규칙은 아래와 같습니다.
- 한글 변수, 메소드 명을 코드스멜로 간주하는 규칙
> 테스트 코드의 픽스쳐에서 한글 변수, 메소드를 사용하므로 아래 규칙은 비활성화 되어야 합니다.
- Class names should comply with a naming convention (java:S101)
- Constant names should comply with a naming convention (java:S115)
- Field names should comply with a naming convention (java:S116)
- Interface names should comply with a naming convention (java:S114)
- Local variable and method parameter names should comply with a naming convention (java:S117)
- Method names should comply with a naming convention (java:S100)
- Static non-final field names should comply with a naming convention (java:S3008)
- 테스트 메소드에서 반드시 assertion을 사용해야하는 규칙
> 인수 테스트 등에서 …

[feat] 소나큐브 Ruleset를 달록 컨벤션에 맞게 수정한다.

---

frontend/src/components/Profile/Profile.tsx

닉네임 UI 고민, 나아가서 프로필 UI 고민을 며칠 동안 했지만 번뜩이는 아이디어가 떠오르지 않네요...
덕분에 다소 늦었습니다 죄송합니다 🫠
'닉네임' 라벨이 닉네임 수정 시에만 나타나는 게 조금 어색하다는 생각은 계속 들더라고요...!
그래서 우선 이거에 대해서만 수정했고 에러 자체는 해결하였습니다!
Closes #543

[fix] 닉네임 수정 버튼 클릭 시 닉네임 입력창과 계정 텍스트가 겹치는 에러를 수정한다.

---

backend/src/docs/asciidoc/auth.adoc
backend/src/docs/asciidoc/category.adoc
backend/src/docs/asciidoc/external-calendar.adoc
backend/src/docs/asciidoc/member.adoc
backend/src/docs/asciidoc/schedule.adoc
backend/src/docs/asciidoc/subscription.adoc
backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/ExternalCalendarControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/SchedulerControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/SubscriptionControllerTest.java

```java
mockMvc.perform( ... )
// ...
.andDo(document("subscription/save", // <-- 여기
```
identifier란 위와 같이 MockMvc `andDo(document())` 에 전달하는 REST Docs 문서 조각에 대한 식별자입니다. 이에 대한 통일이 이뤄지지 않았는데, 아래 형식으로 통일하려 합니다.
```
컨트롤러 이름/컨트롤러 메소드 이름/{설명}
```
`컨트롤러 이름`과 `컨트롤러 메소드 이름` 은 필수고 `설명` 은 선택 사항입니다. _'어떠한 이유로 실패했다'_, 혹은 _'어떤 기준으로 필터링 한다'_ 등 API에 대한 부연설명이 필요한 경우 작성해주시면 됩니다.
- 제목 통일
- Path Parameters를 `PathParameters`, `Path Parameter` 등 으로 통일되지 않게 작성되어있는 부분을 통일합니다.
- 통일 기준은 adoc snippet 파일 명 기준입니다. 만약 파일명이 `.../request-fields.adoc` 이라면, 제목은 `Request Fields` 로 작성합니다.
- 아래 adoc 스니펫은 API에서 사용되지 않을 경우를 제외하고 필수로 문서에 포함해야 합니다. (생략해도 큰 문제가 없다면, 생략합니다.)
- **요청**
- `http-request` : HTTP Request Message
- `request-headers` : Request 헤더 (`requestHeaders()`) (필요한 헤더가 `Authorization` 뿐이라면 생략합니다.)
- …

[refactor] REST docs의 코드 스타일을 통일한다.

---

backend/src/main/java/com/allog/dallog/domain/category/application/ExternalCategoryDetailService.java
backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/IntegrationSchedule.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
backend/src/test/java/com/allog/dallog/domain/category/application/ExternalCategoryDetailServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/composition/application/CalendarServiceTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinderTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionsTest.java
backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java

- CalenderService에서 월별 일정 조회 로직을 제거
--- 
몇가지 객체가 생겨서 주요한 변경점에 대해서 작성해보았습니다🙂
네이밍은 좋은 네이밍은 아닌것 같군요..
**주요한 로직은 memberId를 기반으로 구독한 일정 한달치와 구글 캘린더에 있는일정 한달치를 가져오는 로직을 가지고 있습니다.**
구글 캘린더에 대한 트랜잭션 처리를 제거하는 작업을 처리하기 위해 상위 Service와 유사하게 생성하고 
`Schedule` 패키지 하위에 함께 두었습니다.
객체 id 가 아닌 객체를 기반으로 Repository에서 데이터를 가져오도록 구성해보기 위해 위와 같이 변경해보았습니다🙂
리팩터링을 하면서 양방향 매핑이 되어있으면 `domain`에게 더많은 책임을 줄 수 있는 부분들이 있었는데,
우선은 단방향 매핑만 고려하여 로직을 구성해보았습니다.
추후에, 양방향 매핑을 고려하여 리팩터링을 진행 해도 좋을것 같아요🙂
아직 고쳐야 할 부분이 많네요..!
Closes #600

[refactor] CalenderService에서 월별 일정 조회 로직을 제거한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/domain/IntegrationSchedule.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/Period.java
backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java
backend/src/main/java/com/allog/dallog/infrastructure/oauth/dto/GoogleCalendarEventResponse.java
backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinderTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/IntegrationScheduleTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/PeriodTest.java

종일 일정의 endDateTime을 11시 59분에서 다음 날 00시 00분으로 변경한다.
- 일정 타입 판단 로직이 혹시 잘못 되었는지 꼼꼼히 확인 부탁드립니다.
Closes #592

[refactor] 종일 일정의 endDateTime을 11시 59분에서 다음 날 00시 00분으로 변경한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/IntegrationSchedule.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleRepositoryTest.java

외부 일정 검증 로직을 개선한다.
기존의 Dao에 존재하던 테스트 모두 이전 하였고, 개별 category의 구간 일정 조회 로직을 category list의 구간 일정을 조회하도록 개선하였습니다!
Closes #618

[refactor] 외부 일정 검증 로직을 개선한다.

---

frontend/src/pages/CalendarPage/CalendarPage.styles.ts

(이번 PR에 대한 주의사항은 아니지만 이번에 발견하게 돼서 알아두면 좋을 것 같아 남깁니다)
일정과 `일정 더보기`가 화면 크기가 바뀔 때마다 다르게 보이는데요!
지금은 사용자의 화면 크기가 바뀌어도 리렌더링이 일어나지 않아서 화면의 크기가 작아지면 일정이 넘치게 보일 때가 있네요 🥲
이건 추후 반응형 대응할 때 고려하면 좋을 것 같습니다~!
Closes #628

[style] 달력의 전체 높이를 사용자 화면의 높이에 맞춘다.

---

frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx
frontend/src/hooks/useSchedulePriority.ts

[fix] 종일 일정에 대한 일정 우선순위 계산 에러를 해결한다 & 일정 수정 시 구글 카테고리를 선택할 수 없도록 수정한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/application/CheckedSchedulesFinder.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
backend/src/main/java/com/allog/dallog/domain/schedule/dto/FindSchedulesMaterial.java
backend/src/main/java/com/allog/dallog/domain/schedule/dto/MaterialToFindSchedules.java
backend/src/main/java/com/allog/dallog/presentation/ScheduleController.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/CheckedSchedulesFinderTest.java
backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/presentation/ScheduleControllerTest.java

불필요하게 잡고 있던 트랜잭션 시간을 최소화하기 위해 개선하였습니다.
```java
@Service
public class SubscribingSchedulesFinder {
...
public MemberScheduleResponses findMySubscribingSchedules(final Long memberId, final DateRangeRequest request) {
// Transaction 시작
FindSchedulesMaterial material = scheduleService.findInternalByMemberIdAndDateRange(memberId, request);
// Transaction 끝
List<IntegrationSchedule> schedules = material.getSchedules();
String refreshToken = material.getRefreshToken();
String accessToken = toAccessToken(refreshToken);
List<IntegrationSchedule> externalSchedules = toExternalSchedules(request, material, accessToken);
schedules.addAll(externalSchedules);
return new MemberScheduleResponses(material.getSubscriptions(), new TypedSchedules(schedules));
}
...
}
```
Closes #652

[refactor] 자신의 일정을 조회하는 기능을 개선한다. 

---

backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
backend/src/main/java/com/allog/dallog/domain/auth/domain/TokenRepository.java
backend/src/main/java/com/allog/dallog/domain/auth/dto/response/TokenResponse.java
backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/allog/dallog/common/config/TokenConfig.java
backend/src/test/java/com/allog/dallog/common/fixtures/AuthFixtures.java
backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
backend/src/test/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepositoryTest.java
backend/src/test/java/com/allog/dallog/presentation/AuthControllerTest.java

- 토큰 발급 요청시, 엑세스 토큰과 리프레시 토큰을 모두 발급 
- InMemoryTokenRepository를 통해 리프레시 토큰 발급
- 우선은 적은 FileChanged를 유지하기 위해서 JwtTokenProvider를 통해 RefreshToken도 발급하도록 하였습니다.
- 토큰 발급시 RefreshToken을 InMemoryDb로 저장하도록 하였습니다.
Closes #677

[refactor] 토큰 발급시 AccessToken과 RefreshToken을 모두 발급한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/domain/IntegrationSchedule.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java

코드의 변경이 거의 없습니다. 왜 이렇게 변경하게 되었는지에 대한 과정은 [cyclic dependency](https://dallog.github.io/cyclic-dependency/)에 작성해두었습니다!
Closes #668

[refactor] 패키지 순환 참조를 개선한다.

---

backend/src/docs/asciidoc/category.adoc
backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRole.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleType.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/dto/request/CategoryRoleUpdateRequest.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/exception/NoPermissionToManageRoleException.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/exception/NotAbleToMangeRoleException.java
backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/SubscriptionAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
backend/src/test/java/com/allog/dallog/acceptance/fixtures/SubscriptionAcceptanceFixtures.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleTypeTest.java
backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java

- 카테고리를 생성한 시점에 해당 유저와 카테고리에 대해 ADMIN 역할을 자동으로 생성합니다.
- 구독자의 역할을 변경하는 API를 구현합니다. 이 API는 ADMIN 유저만 실행할 수 있습니다.
- 관리자 유저의 역할을 변경하는 API를 구현합니다. 이 API는 ADMIN 유저만 실행할 수 있습니다.
- 자신이 관리자 유저인 경우, 자신의 역할을 NONE으로 변경하는 API를 구현합니다.
- ADMIN 이 자기자신을 ADMIN이 아닌 역할로 변경할 때, 자기자신이 유일한 ADMIN 인 경우 권한을 변경할 수 없습니다.
#678

[feat] 카테고리 역할 수정 API를 개발한다.

---

backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
backend/src/main/java/com/allog/dallog/domain/externalcalendar/application/ExternalCalendarService.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java

[refactor] N + 1 문제를 개선한다.

---

backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
backend/src/test/java/com/allog/dallog/domain/schedule/domain/ScheduleTest.java

- 지원하지 않는 메서드로 요청시 500 에러가 발생
`HttpRequestMethodNotSupportedException` -> 405로 던진다.
- 특정 년도를 벗어나 일정을 생성/수정하면 500 에러가 발생
스케줄 생성 시 범위 검증 -> 400으로 던진다.
- #697 머지한 이후 머지
Closes #673

특정 상황에서 발생하는 500 에러를 핸들링 한다.

---

backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryTest.java

카테고리 단건 조회 시 타입 체크를 제거한다. 범용적으로 사용하는 단 건 조회의 타입 체크 로직을 제거한다.
Closes #742

[fix] 카테고리 단건 조회 시 타입 체크를 제거한다.

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/components/ScheduleModifyModal/ScheduleModifyModal.tsx

일정 추가/수정 시 카테고리 선택 목록을 편집가능 목록으로 변경한다.
Closes #737

[feat] 일정 추가/수정 시 카테고리 선택 목록을 편집가능 목록으로 변경한다.

---

backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepository.java
backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepositoryTest.java

불필요하게 join을 활용하는 조회 로직을 개선한다.
```java
Optional<OAuthToken> findByMemberId(final Long memberId);
```
```java
Hibernate: 
select
oauthtoken0_.id as id1_4_,
oauthtoken0_.created_at as created_2_4_,
oauthtoken0_.updated_at as updated_3_4_,
oauthtoken0_.members_id as members_5_4_,
oauthtoken0_.refresh_token as refresh_4_4_ 
from
oauth_tokens oauthtoken0_ 
left outer join
members member1_ 
on oauthtoken0_.members_id=member1_.id 
where
member1_.id=?
```
```java
Hibernate: 
select
oauthtoken0_.id as id1_4_,
oauthtoken0_.created_at as created_2_4_,
oauthtoken0_.updated_at as updated_3_4_,
oauthtoken0_.members_id as members_5_4_,
oauthtoken0_.refresh_token as refresh_4_4_ 
from
oauth_tokens oauthtoken0_ 
where
oauthtoken0_.members_id=?
```
Closes #725

[refactor] 불필요하게 join을 활용하는 조회 로직을 개선한다.

---

frontend/src/components/Profile/Profile.tsx
frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
frontend/src/hooks/@queries/category.ts
frontend/src/hooks/@queries/googleCalendar.ts
frontend/src/hooks/@queries/profile.ts
frontend/src/hooks/@queries/schedule.ts
frontend/src/hooks/@queries/subscription.ts

1. `useUserValue`의 user 값을 Profile 컴포넌트 안에서도 사용하고 `usePatchProfile`에서도 사용합니다. `useUserValue`를 각각 호출하는 것보다는 한 번 호출 후 값을 넘겨 사용하는 게 낫다고 판단해서 `usePatchProfile` 인수로 넘겨주었습니다. 나인의 의견도 궁금하네요 🤔
2. `useUserValue` 안에 profile을 get하는 query가 있습니다. 이것도 분리하자니 분리한 훅이 useUserValue 그 자체가 되어버릴 것 같기도 하고, 너무 억지스럽다는 느낌이 강하게 들어 분리하지 않았어요. 이에 대해서도 의견 부탁드립니다~!
3. 커스텀 훅에 사용되는 매개변수 interface 명 정리가 필요해요! 이전에 `useValidateSchedule` 훅을 만들 때에는 `useValidateScheduleParametersType`이라는 이름으로 만들었었네요 😮 query 관련 훅에서는 컴포넌트의 props 타입처럼 ({훅 이름}{Props}) 명명하고 있어요. 정리 한번 하고 넘어가는 거 어떨까요~!
Closes #734

[refactor] 프로필 관련 query를 커스텀 훅으로 분리한다.

---

backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRole.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/exception/NoCategoryAuthorityException.java
backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java

- categoryrole.exception 과 categoryrole.domain 패키지 간의 순환참조 제거
(참고) categoryrole 패키지와 category 패키지간의 순환참조는 https://github.com/woowacourse-teams/2022-dallog/pull/726/files#diff-8fd9a4706fbb13b4b55a165b342318fe620c883525ff0816c1aebd217b7bcd52 에서 제거되었습니다.
😄👍
Closes #721

[feat] 패키지간의 순환 참조를 제거한다.

---

backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRole.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleRepository.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/exception/ManagingCategoryLimitExcessException.java
backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java

> 관리자 != `ADMIN`
> 관리자는 `NONE` 보다 상위 역할을 모두 통칭하는 용어입니다. 그런데 지금은 `NONE` 상위 역할이 `ADMIN` 밖에 없음.
- 카테고리 생성 시 해당 유저가 이미 관리자로 참여하고 있는 카테고리 수가 50개 이상이라면 예외 발생
- 다른 사람이 구독자의 카테고리 역할을 관리자로 변경시, 변경 대상 유저가 이미 관리자로 참여하고 있는 카테고리수가 50개 이상이라면 예외 발생 
Closes #746

[feat] 한 사람이 관리할 수 있는 최대 카테고리 개수 제한을 추가한다. 

---

backend/src/main/java/com/allog/dallog/global/config/TimeZoneConfig.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/member/domain/MemberRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java

스프링 부트 time zone을 위해 configuration 파일을 만들었습니다.
`@PostConstructor` 어노테이션은 메서드가 스프링을 띄울 때 한 번만 실행되게 하는 어노테이션입니다.
- 배포 시 배포 스크립트에서 time zone 설정 옵션을 제거해주어야 합니다.
Closes #786

[feat] 스프링 부트 time zone을 Asia/Seoul로 설정한다.

---

frontend/src/pages/CalendarPage/CalendarPage.tsx

일정이 넘쳐 보이는 달력 에러를 해결한다.
음... 고민을 많이 했는데 `useLayoutEffect`를 사용하게 되었습니다.
1. 어짜피 리렌더링이 많이 발생할 수 밖에 없는 달력페이지 특성상 `useLayoutEffect`를 사용함으로써 더 손해보는 일은 없다고 판단했습니다.
2. 높이를 계산하기 위해 아래처럼 `innerHeight`를 사용한다면 Navbar 헤더부터 계산하는 로직이 너무 복잡해집니단.
```ts
const MAX_SCHEDULE_COUNT = Math.floor(
((window.innerHeight - 64 - 23 - 29 - 56) / (calendar.length / 7) - SCHEDULE.HEIGHT * 4) /
(SCHEDULE.HEIGHT_WITH_MARGIN * 4)
);
```
3. `useEffect` 대신 `useLayoutEffect`를 쓴 이유는 render(요소들의 스타일 속성 계산) 이후, paint(실제 그리기) 이전에 실행되고 동기적으로 실행되기 때문에  실제 그리기 전에 useState의 값을 계산하고 그려지게 됩니다. 즉, `useState`의 값이 0인 상태를 화면에 보여주지 않기 때문에 더 매끄러운 화면을 보여줄 것이라고 기대했습니다.
[useEffect vs useLayoutEffect](https://medium.com/@jnso5072/react-useeffect-%EC%99%80-uselayouteffect-%EC%9D%98-%EC%B0%A8%EC%9D%B4%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C- …

[fix] 일정이 넘쳐 보이는 달력 에러를 해결한다.

---

frontend/src/hooks/@queries/category.ts
frontend/src/hooks/@queries/schedule.ts
frontend/src/hooks/@queries/subscription.ts

카테고리 구독 시 일정이 바로 보이지 않는 에러를 해결한다.
`invalidationQueries`를 진행할 때 어떤 것은 배열 안에 키값을 넣어주고 있고 어떤 것은 그냥 넣어주고 있는데 통일하는게 어떨까요?
Closes #784

[fix] 카테고리 구독 시 일정이 바로 보이지 않는 에러를 해결한다.

---

frontend/src/components/AdminCategoryManageModal/AdminCategoryManageModal.tsx
frontend/src/constants/message.ts
frontend/src/hooks/@queries/category.ts
frontend/src/hooks/@queries/googleCalendar.ts
frontend/src/hooks/@queries/login.ts
frontend/src/hooks/@queries/profile.ts
frontend/src/hooks/@queries/schedule.ts
frontend/src/hooks/@queries/subscription.ts

관리 모달에서 카테고리 이름 수정 시 피드백을 제공한다.
`mutate`는 데이터가 변경되기 때문에 스낵바를 이용하여 피드백을 주는것이 좋다고 느꼈어요.
> 스낵바를 조금 더 적극적으로 사용해 보는건 어떨까요?
✋ queries custom hook들에서 `onSuccess` 로직에 기본적으로 스낵바를 포함시켜주면 좋을것 같은데 어떻게 생각하시나요?
Closes #798

[feat] 관리 모달에서 카테고리 이름 수정 시 피드백을 제공한다.

---

frontend/src/components/AdminCategoryManageModal/AdminCategoryManageModal.styles.ts
frontend/src/components/AdminCategoryManageModal/AdminCategoryManageModal.tsx

카테고리의 관리자가 한 명인 경우 관리 모달에서 권한 포기 영역을 제거한다.
💥 권한 포기 섹션을 지우지 않고 에러메세지와 버튼 disabled 처리를 했습니다. 
(왜 한명일 때 권한 포기 영역이 안보이는지 궁금해하는 유저가 있을수도 있으니까)
Closes #799

[feat] 카테고리의 관리자가 한 명인 경우 관리 모달에서 권한 포기 영역을 제거한다.

---

frontend/src/hooks/@queries/subscription.ts

카테고리 페이지에서 카테고리 구독 시 구독 수가 증가하도록 재요청한다.
1. CACHE_KEY는 기본적으로 `CATEGORY`입니다.
2. `카테고리 단건 (상세)조회` 같은 경우 `[CACHE_KEY.CATEGORY, categoryId]` 로 들어옵니다.
3. `구독`할 때에는 categoryId에 대한 정보가 있어서 invalidationQueries를  `[CACHE_KEY.CATEGORY, categoryId]` 로 진행했습니다.
4. `구독해제`할 때에는 subscriptionId에 대한 정보만으로 mutate가 진행되어서 categoryId에 대한 정보가 없습니다. 그래서 단순히 `CATEGORY`만을 키값으로 주었습니다.
괜찮나요?
Closes #800

[fix] 카테고리 페이지에서 카테고리 구독 시 구독 수가 증가하도록 재요청한다.

---

frontend/src/hooks/@queries/googleCalendar.ts

구글 카테고리 생성 직후 관리 버튼이 보이지 않는 에러를 해결한다.
✨구글 카테고리 추가 후 편집가능한 목록이 변하지 않아서 판단을 제대로 못하고 있었습니다.
Closes #805

[fix] 구글 카테고리 생성 직후 관리 버튼이 보이지 않는 에러를 해결한다.

---

frontend/src/pages/CalendarPage/CalendarPage.styles.ts

일정 더보기의 말줄임 표시를 추가한다.
Closes #811

[fix] 일정 더보기의 말줄임 표시를 추가한다.

---

frontend/src/components/SideGoogleList/SideGoogleList.styles.ts
frontend/src/components/SideSubscribedList/SideSubscribedList.styles.ts

사이드바 카테고리 목록이 없는 경우 관련 문구를 표시한다.
저번 사이드바 스타일 관련 이슈를 해결할때 비어있는 경우를 생각하지 않았었네요 ㅠㅠ
다시 수정했씁니다 😂😂
Closes #827

[fix] 사이드바 카테고리 목록이 없는 경우 관련 문구를 표시한다.

---

frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.styles.ts
frontend/src/components/SubscribedCategoryItem/SubscribedCategoryItem.tsx
frontend/src/constants/message.ts

자신이 생성했던 카테고리를 관리 권한이 없는 상태에서 구독해제 하지 못하는 에러를 해결한다.
✨버튼 disabled 처리를 `creator.id === 내 아이디`로 했었는데 이제는 편집 권한의 여부로 판단하도록 변경했습니다.
이렇게 잘리는 부분을 해결해야할 것 같아요. 답이 떠오르지는 않네요
Closes #803

[fix] 자신이 생성했던 카테고리를 관리 권한이 없는 상태에서 구독해제 하지 못하는 에러를 해결한다.

---

backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepository.java
backend/src/main/java/com/allog/dallog/domain/auth/event/MemberSavedEvent.java
backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/dto/response/MemberWithRoleTypeResponse.java
backend/src/main/java/com/allog/dallog/domain/categoryrole/dto/response/SubscribersResponse.java
backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
backend/src/main/java/com/allog/dallog/domain/subscription/domain/SubscriptionRepository.java
backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
backend/src/test/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/domain/category/domain/CategoryRepositoryTest.java
backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java

- MemberService의 findSubscriber 메서드를 categoryRole 쪽으로 이동
- AuthService에서 멤버 가입 시 이벤트를 발행하는 것으로 다른 도메인에 대한 의존성 제거
[Could not autowire. No beans of type found. error 해결](https://shlee0882.tistory.com/288)
`AuthServiceTest`에서 `events` 필드에 자동주입할 수 없다는 error가 발생합니다. 하지만 실제로는 잘 동작합니다...
이유는 위 링크와 같다는데 굳이 인텔리제이 에러 때문에 componentscan을 붙여줘야하나 싶어서 무시했습니다. 의견 주세여.
https://github.com/woowacourse-teams/2022-dallog/issues/902#issuecomment-1304604061
이벤트 테스트에 대한 고민이 있습니다. 이슈에서 함께 이야기해 보시죠.
Closes #902

[refactor] event를 통해 member와 auth의 다른 도메인 패키지에 대한 의존성을 제거한다.

---

backend/build.gradle
backend/src/main/java/com/allog/dallog/global/config/cache/CacheConfig.java
backend/src/main/java/com/allog/dallog/global/config/cache/ExpiringConcurrentMapCache.java
backend/src/main/java/com/allog/dallog/infrastructure/oauth/client/GoogleExternalCalendarClient.java

`GoogleExternalCalendarClient` 의 `getExternalCalendarSchedules()` 메소드에서 구글 캘린더의 API (외부 API) 를 직접 호출합니다. 이 메소드에 캐시를 적용하여 성능을 개선하였습니다.
캐시 만료 정책에 대해 고민했는데, 일단 15분으로 설정하였습니다. 구글 캘린더는 저희가 통제하고 있는 데이터베이스 같은것이 아니다 보니까 실제 구글 캘린더 일정이 변경되었는지, 변경되지 않았는지는 실제 요청을 하지 않는 이상 알 수가 없어요. 따라서 만료 기한을 너무 길게 잡아두면 유저가 최신 구글 캘린더 정보를 볼 수 없습니다. 그렇다고 너무 짧게 만료 기한을 잡아버리면 너무 자주 캐시 미스가 발생해서 성능이 저하될 수 있어요. 적절한 기한이 필요했습니다.
15분으로 설정한 이유는 다음과 같습니다. 우선 달력 도메인 특성상 유저가 매우 오래 머물며 활동하지 않습니다. 일정을 확인하거나 등록하기 위해 잠깐 방문하는 것이 대부분입니다. 다만 일정을 확인하기 위해 접속 빈도는 높겠죠. 한번 접속하고 일정을 확인하고 관리하고 이탈하는데 시간을 15분가량으로 어림잡았습니다. 정확한 유저 행동 분석은 나중에 [Hotjar](https://www.hotjar.com/) 같은 분석 도구를 사용하면 좋을 것 같습니다.
제목은 거창한데 별거는 아닙니다. 스프링은 `ConcurrentHashMap` 을 사용한 `ConcurrentMapCache` 라는 캐시 구현체를 기본으로 제공합니다. 이 친구는 별도 설정없어도 바로 사용할 수 있는 장점이 있는데, 기능이 매우 빈약합니다. 특히 TTL …

[feat] 외부 캘린더 요청 API 결과를 캐싱하여 성능을 최적화한다. 

---

backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/com/allog/dallog/auth/presentation/AuthControllerTest.java
backend/src/test/java/com/allog/dallog/category/application/CategoryServiceTest.java
backend/src/test/java/com/allog/dallog/category/application/ExternalCategoryDetailServiceTest.java
backend/src/test/java/com/allog/dallog/category/presentation/CategoryControllerTest.java
backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
backend/src/test/java/com/allog/dallog/common/annotation/ControllerTest.java
backend/src/test/java/com/allog/dallog/common/annotation/RepositoryTest.java
backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
backend/src/test/java/com/allog/dallog/common/builder/BuilderSupporter.java
backend/src/test/java/com/allog/dallog/common/builder/GivenBuilder.java
backend/src/test/java/com/allog/dallog/externalcalendar/application/ExternalCalendarServiceTest.java
backend/src/test/java/com/allog/dallog/externalcalendar/presentation/ExternalCalendarControllerTest.java
backend/src/test/java/com/allog/dallog/infrastructure/oauth/client/StubOAuthClient.java
backend/src/test/java/com/allog/dallog/member/application/MemberServiceTest.java
backend/src/test/java/com/allog/dallog/member/presentation/MemberControllerTest.java
backend/src/test/java/com/allog/dallog/schedule/application/ScheduleServiceTest.java
backend/src/test/java/com/allog/dallog/schedule/presentation/ScheduleControllerTest.java
backend/src/test/java/com/allog/dallog/subscription/application/SubscriptionServiceTest.java
backend/src/test/java/com/allog/dallog/subscription/presentation/SubscriptionControllerTest.java

- 각 `ServiceTest`의 innerClass들을 제거하고 `GivenBuilder`를 `common`패키지로 이동하였습니다.
- `GivenBuilder`의 로직수행을 위한 `repository` 의존주입을 위해 `BuilderSupporter` 빈을 생성하였습니다.
- `BuilderSupporter`에는 전체 `repository` 빈에대해 의존성을 가지고 있습니다
Closes #918

[refactor] ServiceTest의 중첩클래스를 제거한다.
